version: "3.6"

services:
  payone-billing-service-go:
    build: .
    container_name: payone-billing-service-go
    networks:
      - p1devnet
    restart: always
    ports:
      - "8086:8086"
    environment:
      MONGO_HOST: "payone-mongo:27017"
      MONGO_DB: p1payapi
      MONGO_USER: ""
      MONGO_PASSWORD: ""
      CENTRIFUGO_SECRET: "secret"
      CARD_PAY_API_URL: "https://sandbox.cardpay.com"
      BROKER_ADDRESS: "amqp://rabbitmq:5672"
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: consul
    tty: true

networks:
  p1devnet:
    external: true