// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/grpc.proto

package grpc // import "github.com/paysuper/paysuper-billing-server/pkg/proto/grpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import billing "github.com/paysuper/paysuper-billing-server/pkg/proto/billing"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{0}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{1}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type PaymentCreateRequest struct {
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentCreateRequest) Reset()         { *m = PaymentCreateRequest{} }
func (m *PaymentCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentCreateRequest) ProtoMessage()    {}
func (*PaymentCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{2}
}
func (m *PaymentCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentCreateRequest.Unmarshal(m, b)
}
func (m *PaymentCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentCreateRequest.Marshal(b, m, deterministic)
}
func (dst *PaymentCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentCreateRequest.Merge(dst, src)
}
func (m *PaymentCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentCreateRequest.Size(m)
}
func (m *PaymentCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentCreateRequest proto.InternalMessageInfo

func (m *PaymentCreateRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type PaymentCreateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RedirectUrl          string   `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentCreateResponse) Reset()         { *m = PaymentCreateResponse{} }
func (m *PaymentCreateResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentCreateResponse) ProtoMessage()    {}
func (*PaymentCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{3}
}
func (m *PaymentCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentCreateResponse.Unmarshal(m, b)
}
func (m *PaymentCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentCreateResponse.Marshal(b, m, deterministic)
}
func (dst *PaymentCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentCreateResponse.Merge(dst, src)
}
func (m *PaymentCreateResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentCreateResponse.Size(m)
}
func (m *PaymentCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentCreateResponse proto.InternalMessageInfo

func (m *PaymentCreateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PaymentCreateResponse) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

func (m *PaymentCreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PaymentFormJsonDataRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Scheme               string   `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentFormJsonDataRequest) Reset()         { *m = PaymentFormJsonDataRequest{} }
func (m *PaymentFormJsonDataRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentFormJsonDataRequest) ProtoMessage()    {}
func (*PaymentFormJsonDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{4}
}
func (m *PaymentFormJsonDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentFormJsonDataRequest.Unmarshal(m, b)
}
func (m *PaymentFormJsonDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentFormJsonDataRequest.Marshal(b, m, deterministic)
}
func (dst *PaymentFormJsonDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentFormJsonDataRequest.Merge(dst, src)
}
func (m *PaymentFormJsonDataRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentFormJsonDataRequest.Size(m)
}
func (m *PaymentFormJsonDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentFormJsonDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentFormJsonDataRequest proto.InternalMessageInfo

func (m *PaymentFormJsonDataRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PaymentFormJsonDataRequest) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *PaymentFormJsonDataRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type PaymentFormJsonDataProject struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: json:"url_success,omitempty"
	UrlSuccess string `protobuf:"bytes,2,opt,name=url_success,json=urlSuccess,proto3" json:"url_success,omitempty"`
	// @inject_tag: json:"url_fail,omitempty"
	UrlFail              string   `protobuf:"bytes,3,opt,name=url_fail,json=urlFail,proto3" json:"url_fail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentFormJsonDataProject) Reset()         { *m = PaymentFormJsonDataProject{} }
func (m *PaymentFormJsonDataProject) String() string { return proto.CompactTextString(m) }
func (*PaymentFormJsonDataProject) ProtoMessage()    {}
func (*PaymentFormJsonDataProject) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{5}
}
func (m *PaymentFormJsonDataProject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentFormJsonDataProject.Unmarshal(m, b)
}
func (m *PaymentFormJsonDataProject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentFormJsonDataProject.Marshal(b, m, deterministic)
}
func (dst *PaymentFormJsonDataProject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentFormJsonDataProject.Merge(dst, src)
}
func (m *PaymentFormJsonDataProject) XXX_Size() int {
	return xxx_messageInfo_PaymentFormJsonDataProject.Size(m)
}
func (m *PaymentFormJsonDataProject) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentFormJsonDataProject.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentFormJsonDataProject proto.InternalMessageInfo

func (m *PaymentFormJsonDataProject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentFormJsonDataProject) GetUrlSuccess() string {
	if m != nil {
		return m.UrlSuccess
	}
	return ""
}

func (m *PaymentFormJsonDataProject) GetUrlFail() string {
	if m != nil {
		return m.UrlFail
	}
	return ""
}

type PaymentFormJsonDataResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"account,omitempty"
	Account               string                              `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	HasVat                bool                                `protobuf:"varint,3,opt,name=has_vat,json=hasVat,proto3" json:"has_vat,omitempty"`
	HasUserCommission     bool                                `protobuf:"varint,4,opt,name=has_user_commission,json=hasUserCommission,proto3" json:"has_user_commission,omitempty"`
	Project               *PaymentFormJsonDataProject         `protobuf:"bytes,5,opt,name=project,proto3" json:"project,omitempty"`
	PaymentMethods        []*billing.PaymentFormPaymentMethod `protobuf:"bytes,6,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	InlineFormRedirectUrl string                              `protobuf:"bytes,7,opt,name=inline_form_redirect_url,json=inlineFormRedirectUrl,proto3" json:"inline_form_redirect_url,omitempty"`
	Token                 string                              `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                            `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized      []byte                              `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache         int32                               `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentFormJsonDataResponse) Reset()         { *m = PaymentFormJsonDataResponse{} }
func (m *PaymentFormJsonDataResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentFormJsonDataResponse) ProtoMessage()    {}
func (*PaymentFormJsonDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{6}
}
func (m *PaymentFormJsonDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentFormJsonDataResponse.Unmarshal(m, b)
}
func (m *PaymentFormJsonDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentFormJsonDataResponse.Marshal(b, m, deterministic)
}
func (dst *PaymentFormJsonDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentFormJsonDataResponse.Merge(dst, src)
}
func (m *PaymentFormJsonDataResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentFormJsonDataResponse.Size(m)
}
func (m *PaymentFormJsonDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentFormJsonDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentFormJsonDataResponse proto.InternalMessageInfo

func (m *PaymentFormJsonDataResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentFormJsonDataResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PaymentFormJsonDataResponse) GetHasVat() bool {
	if m != nil {
		return m.HasVat
	}
	return false
}

func (m *PaymentFormJsonDataResponse) GetHasUserCommission() bool {
	if m != nil {
		return m.HasUserCommission
	}
	return false
}

func (m *PaymentFormJsonDataResponse) GetProject() *PaymentFormJsonDataProject {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *PaymentFormJsonDataResponse) GetPaymentMethods() []*billing.PaymentFormPaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

func (m *PaymentFormJsonDataResponse) GetInlineFormRedirectUrl() string {
	if m != nil {
		return m.InlineFormRedirectUrl
	}
	return ""
}

func (m *PaymentFormJsonDataResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PaymentNotifyRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Request              []byte   `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentNotifyRequest) Reset()         { *m = PaymentNotifyRequest{} }
func (m *PaymentNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentNotifyRequest) ProtoMessage()    {}
func (*PaymentNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{7}
}
func (m *PaymentNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentNotifyRequest.Unmarshal(m, b)
}
func (m *PaymentNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentNotifyRequest.Marshal(b, m, deterministic)
}
func (dst *PaymentNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentNotifyRequest.Merge(dst, src)
}
func (m *PaymentNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentNotifyRequest.Size(m)
}
func (m *PaymentNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentNotifyRequest proto.InternalMessageInfo

func (m *PaymentNotifyRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PaymentNotifyRequest) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PaymentNotifyRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type PaymentNotifyResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *PaymentNotifyResponse) Reset()         { *m = PaymentNotifyResponse{} }
func (m *PaymentNotifyResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentNotifyResponse) ProtoMessage()    {}
func (*PaymentNotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{8}
}
func (m *PaymentNotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentNotifyResponse.Unmarshal(m, b)
}
func (m *PaymentNotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentNotifyResponse.Marshal(b, m, deterministic)
}
func (dst *PaymentNotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentNotifyResponse.Merge(dst, src)
}
func (m *PaymentNotifyResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentNotifyResponse.Size(m)
}
func (m *PaymentNotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentNotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentNotifyResponse proto.InternalMessageInfo

func (m *PaymentNotifyResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PaymentNotifyResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ConvertRateRequest struct {
	From                 int32    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ConvertRateRequest) Reset()         { *m = ConvertRateRequest{} }
func (m *ConvertRateRequest) String() string { return proto.CompactTextString(m) }
func (*ConvertRateRequest) ProtoMessage()    {}
func (*ConvertRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{9}
}
func (m *ConvertRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertRateRequest.Unmarshal(m, b)
}
func (m *ConvertRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertRateRequest.Marshal(b, m, deterministic)
}
func (dst *ConvertRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertRateRequest.Merge(dst, src)
}
func (m *ConvertRateRequest) XXX_Size() int {
	return xxx_messageInfo_ConvertRateRequest.Size(m)
}
func (m *ConvertRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertRateRequest proto.InternalMessageInfo

func (m *ConvertRateRequest) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ConvertRateRequest) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

type ConvertRateResponse struct {
	Rate                 float64  `protobuf:"fixed64,1,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *ConvertRateResponse) Reset()         { *m = ConvertRateResponse{} }
func (m *ConvertRateResponse) String() string { return proto.CompactTextString(m) }
func (*ConvertRateResponse) ProtoMessage()    {}
func (*ConvertRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{10}
}
func (m *ConvertRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertRateResponse.Unmarshal(m, b)
}
func (m *ConvertRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertRateResponse.Marshal(b, m, deterministic)
}
func (dst *ConvertRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertRateResponse.Merge(dst, src)
}
func (m *ConvertRateResponse) XXX_Size() int {
	return xxx_messageInfo_ConvertRateResponse.Size(m)
}
func (m *ConvertRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertRateResponse proto.InternalMessageInfo

func (m *ConvertRateResponse) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type OnboardingBanking struct {
	// @inject_tag: validate:"required,len=3"
	Currency string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty" validate:"required,len=3"`
	// @inject_tag: validate:"required"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	AccountNumber string `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	Swift                string   `protobuf:"bytes,5,opt,name=swift,proto3" json:"swift,omitempty" validate:"required"`
	Details              string   `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *OnboardingBanking) Reset()         { *m = OnboardingBanking{} }
func (m *OnboardingBanking) String() string { return proto.CompactTextString(m) }
func (*OnboardingBanking) ProtoMessage()    {}
func (*OnboardingBanking) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{11}
}
func (m *OnboardingBanking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnboardingBanking.Unmarshal(m, b)
}
func (m *OnboardingBanking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnboardingBanking.Marshal(b, m, deterministic)
}
func (dst *OnboardingBanking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnboardingBanking.Merge(dst, src)
}
func (m *OnboardingBanking) XXX_Size() int {
	return xxx_messageInfo_OnboardingBanking.Size(m)
}
func (m *OnboardingBanking) XXX_DiscardUnknown() {
	xxx_messageInfo_OnboardingBanking.DiscardUnknown(m)
}

var xxx_messageInfo_OnboardingBanking proto.InternalMessageInfo

func (m *OnboardingBanking) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *OnboardingBanking) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OnboardingBanking) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OnboardingBanking) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *OnboardingBanking) GetSwift() string {
	if m != nil {
		return m.Swift
	}
	return ""
}

func (m *OnboardingBanking) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type OnboardingRequest struct {
	// @inject_tag: validate:"required,hexadecimal,len=24"
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty" validate:"required,hexadecimal,len=24"`
	// @inject_tag: validate:"required,email"
	AccountingEmail string `protobuf:"bytes,2,opt,name=accounting_email,json=accountingEmail,proto3" json:"accounting_email,omitempty" validate:"required,email"`
	// @inject_tag: validate:"required"
	Name            string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" validate:"required"`
	AlternativeName string `protobuf:"bytes,4,opt,name=alternative_name,json=alternativeName,proto3" json:"alternative_name,omitempty"`
	// @inject_tag: validate:"required"
	Website string `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty" validate:"required"`
	// @inject_tag: validate:"required,len=2"
	Country string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty" validate:"required,len=2"`
	// @inject_tag: validate:"required"
	State string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	Zip string `protobuf:"bytes,8,opt,name=zip,proto3" json:"zip,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	City string `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	Address           string `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty" validate:"required"`
	AddressAdditional string `protobuf:"bytes,11,opt,name=address_additional,json=addressAdditional,proto3" json:"address_additional,omitempty"`
	// @inject_tag: validate:"required"
	RegistrationNumber string `protobuf:"bytes,12,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	TaxId string `protobuf:"bytes,13,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty" validate:"required"`
	// @inject_tag: validate:"required,dive"
	Contacts *billing.MerchantContact `protobuf:"bytes,14,opt,name=contacts,proto3" json:"contacts,omitempty" validate:"required,dive"`
	// @inject_tag: validate:"required,dive"
	Banking              *OnboardingBanking `protobuf:"bytes,15,opt,name=banking,proto3" json:"banking,omitempty" validate:"required,dive"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *OnboardingRequest) Reset()         { *m = OnboardingRequest{} }
func (m *OnboardingRequest) String() string { return proto.CompactTextString(m) }
func (*OnboardingRequest) ProtoMessage()    {}
func (*OnboardingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{12}
}
func (m *OnboardingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnboardingRequest.Unmarshal(m, b)
}
func (m *OnboardingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnboardingRequest.Marshal(b, m, deterministic)
}
func (dst *OnboardingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnboardingRequest.Merge(dst, src)
}
func (m *OnboardingRequest) XXX_Size() int {
	return xxx_messageInfo_OnboardingRequest.Size(m)
}
func (m *OnboardingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnboardingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnboardingRequest proto.InternalMessageInfo

func (m *OnboardingRequest) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *OnboardingRequest) GetAccountingEmail() string {
	if m != nil {
		return m.AccountingEmail
	}
	return ""
}

func (m *OnboardingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OnboardingRequest) GetAlternativeName() string {
	if m != nil {
		return m.AlternativeName
	}
	return ""
}

func (m *OnboardingRequest) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *OnboardingRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *OnboardingRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *OnboardingRequest) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *OnboardingRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *OnboardingRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OnboardingRequest) GetAddressAdditional() string {
	if m != nil {
		return m.AddressAdditional
	}
	return ""
}

func (m *OnboardingRequest) GetRegistrationNumber() string {
	if m != nil {
		return m.RegistrationNumber
	}
	return ""
}

func (m *OnboardingRequest) GetTaxId() string {
	if m != nil {
		return m.TaxId
	}
	return ""
}

func (m *OnboardingRequest) GetContacts() *billing.MerchantContact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *OnboardingRequest) GetBanking() *OnboardingBanking {
	if m != nil {
		return m.Banking
	}
	return nil
}

type FindByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *FindByIdRequest) Reset()         { *m = FindByIdRequest{} }
func (m *FindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindByIdRequest) ProtoMessage()    {}
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{13}
}
func (m *FindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIdRequest.Unmarshal(m, b)
}
func (m *FindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIdRequest.Marshal(b, m, deterministic)
}
func (dst *FindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIdRequest.Merge(dst, src)
}
func (m *FindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindByIdRequest.Size(m)
}
func (m *FindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIdRequest proto.InternalMessageInfo

func (m *FindByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MerchantListingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OnlyWithAgreement    bool     `protobuf:"varint,2,opt,name=only_with_agreement,json=onlyWithAgreement,proto3" json:"only_with_agreement,omitempty"`
	LastPayoutDateFrom   int64    `protobuf:"varint,3,opt,name=last_payout_date_from,json=lastPayoutDateFrom,proto3" json:"last_payout_date_from,omitempty"`
	LastPayoutDateTo     int64    `protobuf:"varint,4,opt,name=last_payout_date_to,json=lastPayoutDateTo,proto3" json:"last_payout_date_to,omitempty"`
	LastPayoutAmount     float64  `protobuf:"fixed64,5,opt,name=last_payout_amount,json=lastPayoutAmount,proto3" json:"last_payout_amount,omitempty"`
	Sort                 []string `protobuf:"bytes,6,rep,name=sort,proto3" json:"sort,omitempty"`
	Limit                int32    `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *MerchantListingRequest) Reset()         { *m = MerchantListingRequest{} }
func (m *MerchantListingRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantListingRequest) ProtoMessage()    {}
func (*MerchantListingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{14}
}
func (m *MerchantListingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantListingRequest.Unmarshal(m, b)
}
func (m *MerchantListingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantListingRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantListingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantListingRequest.Merge(dst, src)
}
func (m *MerchantListingRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantListingRequest.Size(m)
}
func (m *MerchantListingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantListingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantListingRequest proto.InternalMessageInfo

func (m *MerchantListingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantListingRequest) GetOnlyWithAgreement() bool {
	if m != nil {
		return m.OnlyWithAgreement
	}
	return false
}

func (m *MerchantListingRequest) GetLastPayoutDateFrom() int64 {
	if m != nil {
		return m.LastPayoutDateFrom
	}
	return 0
}

func (m *MerchantListingRequest) GetLastPayoutDateTo() int64 {
	if m != nil {
		return m.LastPayoutDateTo
	}
	return 0
}

func (m *MerchantListingRequest) GetLastPayoutAmount() float64 {
	if m != nil {
		return m.LastPayoutAmount
	}
	return 0
}

func (m *MerchantListingRequest) GetSort() []string {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *MerchantListingRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MerchantListingRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Merchants struct {
	Merchants            []*billing.Merchant `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte              `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32               `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *Merchants) Reset()         { *m = Merchants{} }
func (m *Merchants) String() string { return proto.CompactTextString(m) }
func (*Merchants) ProtoMessage()    {}
func (*Merchants) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{15}
}
func (m *Merchants) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Merchants.Unmarshal(m, b)
}
func (m *Merchants) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Merchants.Marshal(b, m, deterministic)
}
func (dst *Merchants) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchants.Merge(dst, src)
}
func (m *Merchants) XXX_Size() int {
	return xxx_messageInfo_Merchants.Size(m)
}
func (m *Merchants) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchants.DiscardUnknown(m)
}

var xxx_messageInfo_Merchants proto.InternalMessageInfo

func (m *Merchants) GetMerchants() []*billing.Merchant {
	if m != nil {
		return m.Merchants
	}
	return nil
}

type MerchantChangeStatusRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *MerchantChangeStatusRequest) Reset()         { *m = MerchantChangeStatusRequest{} }
func (m *MerchantChangeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantChangeStatusRequest) ProtoMessage()    {}
func (*MerchantChangeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a4e55ea1efe9a072, []int{16}
}
func (m *MerchantChangeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantChangeStatusRequest.Unmarshal(m, b)
}
func (m *MerchantChangeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantChangeStatusRequest.Marshal(b, m, deterministic)
}
func (dst *MerchantChangeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantChangeStatusRequest.Merge(dst, src)
}
func (m *MerchantChangeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantChangeStatusRequest.Size(m)
}
func (m *MerchantChangeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantChangeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantChangeStatusRequest proto.InternalMessageInfo

func (m *MerchantChangeStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MerchantChangeStatusRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "grpc.EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "grpc.EmptyResponse")
	proto.RegisterType((*PaymentCreateRequest)(nil), "grpc.PaymentCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "grpc.PaymentCreateRequest.DataEntry")
	proto.RegisterType((*PaymentCreateResponse)(nil), "grpc.PaymentCreateResponse")
	proto.RegisterType((*PaymentFormJsonDataRequest)(nil), "grpc.PaymentFormJsonDataRequest")
	proto.RegisterType((*PaymentFormJsonDataProject)(nil), "grpc.PaymentFormJsonDataProject")
	proto.RegisterType((*PaymentFormJsonDataResponse)(nil), "grpc.PaymentFormJsonDataResponse")
	proto.RegisterType((*PaymentNotifyRequest)(nil), "grpc.PaymentNotifyRequest")
	proto.RegisterType((*PaymentNotifyResponse)(nil), "grpc.PaymentNotifyResponse")
	proto.RegisterType((*ConvertRateRequest)(nil), "grpc.ConvertRateRequest")
	proto.RegisterType((*ConvertRateResponse)(nil), "grpc.ConvertRateResponse")
	proto.RegisterType((*OnboardingBanking)(nil), "grpc.OnboardingBanking")
	proto.RegisterType((*OnboardingRequest)(nil), "grpc.OnboardingRequest")
	proto.RegisterType((*FindByIdRequest)(nil), "grpc.FindByIdRequest")
	proto.RegisterType((*MerchantListingRequest)(nil), "grpc.MerchantListingRequest")
	proto.RegisterType((*Merchants)(nil), "grpc.Merchants")
	proto.RegisterType((*MerchantChangeStatusRequest)(nil), "grpc.MerchantChangeStatusRequest")
}

func init() { proto.RegisterFile("grpc/grpc.proto", fileDescriptor_grpc_a4e55ea1efe9a072) }

var fileDescriptor_grpc_a4e55ea1efe9a072 = []byte{
	// 1378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x6d, 0x4f, 0x1b, 0xc7,
	0x13, 0xc7, 0xc6, 0x60, 0x3c, 0x80, 0x1d, 0x96, 0x90, 0x5c, 0x4c, 0xa4, 0xc0, 0xe9, 0xff, 0x97,
	0x12, 0xa9, 0x80, 0x92, 0x46, 0x4a, 0x8a, 0xd2, 0xaa, 0x81, 0x98, 0x88, 0xa8, 0x21, 0xf4, 0x68,
	0x5a, 0xa9, 0x6f, 0x4e, 0xeb, 0xbb, 0xb5, 0xbd, 0xe5, 0x6e, 0xd7, 0xdd, 0xdd, 0x23, 0x71, 0x3f,
	0x41, 0xfb, 0x65, 0xaa, 0xbe, 0xe8, 0x77, 0xea, 0xd7, 0xa8, 0xf6, 0xe1, 0xce, 0x77, 0xd8, 0xa4,
	0xed, 0x1b, 0x98, 0xe7, 0xd9, 0x99, 0xfd, 0xcd, 0xec, 0x19, 0x3a, 0x43, 0x31, 0x8e, 0x0e, 0xf4,
	0x9f, 0xfd, 0xb1, 0xe0, 0x8a, 0xa3, 0x86, 0xa6, 0xbb, 0x5b, 0x7d, 0x9a, 0x24, 0x94, 0x0d, 0x0f,
	0xdc, 0x7f, 0xab, 0xf4, 0xdb, 0xb0, 0xd6, 0x4b, 0xc7, 0x6a, 0x12, 0x90, 0x9f, 0x33, 0x22, 0x95,
	0xdf, 0x81, 0x75, 0xc7, 0xcb, 0x31, 0x67, 0x92, 0xf8, 0xbf, 0xd5, 0xe0, 0xf6, 0x39, 0x9e, 0xa4,
	0x84, 0xa9, 0x63, 0x41, 0xb0, 0x22, 0xce, 0x12, 0x3d, 0x87, 0x46, 0x8c, 0x15, 0xf6, 0x6a, 0x3b,
	0x8b, 0x0f, 0x57, 0x9f, 0xfc, 0x6f, 0xdf, 0x64, 0x9c, 0x67, 0xb9, 0xff, 0x0a, 0x2b, 0xdc, 0x63,
	0x4a, 0x4c, 0x02, 0xe3, 0xd1, 0x7d, 0x06, 0xad, 0x42, 0x84, 0x6e, 0xc1, 0xe2, 0x25, 0x99, 0x78,
	0xb5, 0x9d, 0xda, 0xc3, 0x56, 0xa0, 0x49, 0x74, 0x1b, 0x96, 0xae, 0x70, 0x92, 0x11, 0xaf, 0x6e,
	0x64, 0x96, 0x39, 0xac, 0x3f, 0xaf, 0xf9, 0x23, 0xd8, 0xba, 0x96, 0xc0, 0x1e, 0x12, 0xdd, 0x81,
	0x65, 0xa9, 0xb0, 0xca, 0xa4, 0x89, 0xb3, 0x14, 0x38, 0x0e, 0xed, 0xc2, 0x9a, 0x20, 0x31, 0x15,
	0x24, 0x52, 0x61, 0x26, 0x12, 0x17, 0x71, 0x35, 0x97, 0xbd, 0x17, 0x89, 0xce, 0x46, 0x84, 0xe0,
	0xc2, 0x5b, 0xb4, 0xd9, 0x0c, 0xe3, 0x47, 0xd0, 0x75, 0x99, 0x4e, 0xb8, 0x48, 0xdf, 0x48, 0xce,
	0xf4, 0x89, 0xf3, 0xd2, 0xef, 0xc1, 0x0a, 0x17, 0x31, 0x11, 0x21, 0x8d, 0xdd, 0xc1, 0x9b, 0x86,
	0x3f, 0x8d, 0xcd, 0x49, 0xa2, 0x11, 0x49, 0xf3, 0xd3, 0x3b, 0x0e, 0x21, 0x68, 0x8c, 0xb8, 0x54,
	0x2e, 0x8b, 0xa1, 0xfd, 0x64, 0x6e, 0x92, 0x73, 0xc1, 0x7f, 0x22, 0x91, 0xd2, 0x1e, 0x0c, 0xa7,
	0xc4, 0x25, 0x30, 0x34, 0x7a, 0x00, 0xab, 0x99, 0x48, 0x42, 0x99, 0x45, 0x11, 0x91, 0xd2, 0xa5,
	0x80, 0x4c, 0x24, 0x17, 0x56, 0xa2, 0x4f, 0xa6, 0x0d, 0x06, 0x98, 0x26, 0x2e, 0x55, 0x33, 0x13,
	0xc9, 0x09, 0xa6, 0x89, 0xff, 0x57, 0x1d, 0xb6, 0xe7, 0xd6, 0xe4, 0x7a, 0xd8, 0x86, 0x7a, 0x51,
	0x4e, 0x9d, 0xc6, 0xc8, 0x83, 0x26, 0x8e, 0x22, 0x9e, 0x31, 0xe5, 0xf2, 0xe4, 0x2c, 0xba, 0x0b,
	0xcd, 0x11, 0x96, 0xe1, 0x15, 0xb6, 0xe5, 0xac, 0x04, 0xcb, 0x23, 0x2c, 0xbf, 0xc7, 0x0a, 0xed,
	0xc3, 0xa6, 0x56, 0x64, 0x92, 0x88, 0x30, 0xe2, 0x69, 0x4a, 0xa5, 0xa4, 0x9c, 0x79, 0x0d, 0x63,
	0xb4, 0x31, 0xc2, 0xf2, 0xbd, 0x24, 0xe2, 0xb8, 0x50, 0xa0, 0x43, 0x68, 0x8e, 0x6d, 0xb5, 0xde,
	0xd2, 0x4e, 0xed, 0xe1, 0xea, 0x93, 0x9d, 0x0a, 0x8a, 0xe6, 0x74, 0x25, 0xc8, 0x1d, 0xd0, 0x1b,
	0xe8, 0x8c, 0xad, 0x59, 0x98, 0x12, 0x35, 0xe2, 0xb1, 0xf4, 0x96, 0x0d, 0x12, 0x77, 0xf7, 0x73,
	0x84, 0x97, 0xc2, 0x38, 0xf2, 0xad, 0xb1, 0x0c, 0xda, 0xe3, 0x32, 0x2b, 0xd1, 0x33, 0xf0, 0x28,
	0x4b, 0x28, 0x23, 0xe1, 0x80, 0x8b, 0x34, 0xac, 0x40, 0xa6, 0x69, 0x6a, 0xdf, 0xb2, 0x7a, 0x1d,
	0x2a, 0xa8, 0x82, 0x47, 0xf1, 0x4b, 0xc2, 0xbc, 0x15, 0x0b, 0x1e, 0xc3, 0xf8, 0xb4, 0x98, 0x98,
	0x33, 0xae, 0xe8, 0x60, 0xf2, 0x2f, 0x60, 0xe3, 0x41, 0x53, 0x58, 0x2b, 0xd3, 0xec, 0xb5, 0x20,
	0x67, 0xd1, 0x7d, 0x68, 0x49, 0x3a, 0x64, 0x58, 0x65, 0x82, 0xb8, 0x2b, 0x9d, 0x0a, 0xfc, 0x5e,
	0x31, 0x11, 0x79, 0xaa, 0x7f, 0x98, 0x88, 0x02, 0xee, 0xf5, 0x32, 0xdc, 0x9f, 0x03, 0x3a, 0xe6,
	0xec, 0x8a, 0x08, 0x15, 0x94, 0x26, 0x1c, 0x41, 0x63, 0x20, 0x78, 0xea, 0x22, 0x18, 0x5a, 0xa3,
	0x44, 0x71, 0xe3, 0xbc, 0x14, 0xd4, 0x15, 0xf7, 0x1f, 0xc1, 0x66, 0xc5, 0xd3, 0xa5, 0x47, 0xd0,
	0x10, 0x58, 0x59, 0xf0, 0xd6, 0x02, 0x43, 0xfb, 0x7f, 0xd6, 0x60, 0xe3, 0x1d, 0xeb, 0x73, 0x2c,
	0x62, 0xca, 0x86, 0x47, 0x98, 0x5d, 0x52, 0x36, 0x44, 0x5d, 0x58, 0x89, 0x32, 0x21, 0x08, 0x8b,
	0xf2, 0x25, 0x50, 0xf0, 0xc5, 0x08, 0xd4, 0x4b, 0x23, 0xa0, 0x61, 0x19, 0xc7, 0x42, 0xc3, 0xdf,
	0x01, 0xdc, 0xb1, 0xe8, 0xff, 0xd0, 0x76, 0x08, 0x0d, 0x59, 0x96, 0xf6, 0x89, 0x30, 0xc0, 0x6b,
	0x05, 0xeb, 0x4e, 0x7a, 0x66, 0x84, 0xba, 0x03, 0xf2, 0x03, 0x1d, 0x58, 0xc8, 0xb5, 0x02, 0xcb,
	0xe8, 0xb0, 0x31, 0x51, 0x98, 0x26, 0x1a, 0x46, 0x26, 0xac, 0x63, 0xfd, 0x5f, 0x1b, 0xe5, 0x63,
	0xe7, 0xbd, 0x79, 0x00, 0xab, 0xe4, 0xa3, 0x22, 0x82, 0xe1, 0x64, 0x7a, 0x9d, 0x90, 0x8b, 0x4e,
	0x63, 0xf4, 0x08, 0x6e, 0xb9, 0xbc, 0x94, 0x0d, 0x43, 0x92, 0xea, 0x89, 0xb4, 0x75, 0x74, 0xa6,
	0xf2, 0x9e, 0x16, 0x17, 0x65, 0x2e, 0x96, 0xca, 0xd4, 0xee, 0x89, 0x09, 0xa6, 0xe8, 0x15, 0x09,
	0x8d, 0xbe, 0xe1, 0xdc, 0xa7, 0xf2, 0x33, 0xd7, 0x91, 0x0f, 0xa4, 0x2f, 0xa9, 0x22, 0xae, 0xa4,
	0x9c, 0xd5, 0x1a, 0x93, 0x49, 0x4c, 0xf2, 0xa2, 0x1c, 0x6b, 0x9a, 0xa0, 0xf4, 0x05, 0x35, 0x5d,
	0x13, 0x34, 0xa3, 0x77, 0xf1, 0x2f, 0x74, 0xec, 0xc0, 0xac, 0x49, 0x7d, 0xb4, 0x88, 0xaa, 0x89,
	0xd7, 0xb2, 0x47, 0xd3, 0x74, 0xf9, 0x06, 0xa0, 0x7a, 0x03, 0x7b, 0x80, 0x1c, 0x19, 0xe2, 0x38,
	0xa6, 0x8a, 0x72, 0x86, 0x13, 0x6f, 0xd5, 0x18, 0x6d, 0x38, 0xcd, 0xcb, 0x42, 0x81, 0x0e, 0x60,
	0x53, 0x90, 0x21, 0x95, 0x4a, 0x60, 0x2d, 0xc9, 0x6f, 0x6d, 0xcd, 0xd8, 0xa3, 0xb2, 0xca, 0x5d,
	0xdd, 0x16, 0x2c, 0x2b, 0xfc, 0x51, 0xf7, 0x7b, 0xdd, 0xcd, 0x1b, 0xfe, 0x78, 0x1a, 0xa3, 0xa7,
	0xb0, 0x12, 0x71, 0xa6, 0x70, 0xa4, 0xa4, 0xd7, 0x36, 0x7b, 0xc4, 0x2b, 0x76, 0xc0, 0x5b, 0x22,
	0xa2, 0x11, 0x66, 0xea, 0xd8, 0x1a, 0x04, 0x85, 0x25, 0x7a, 0x0c, 0xcd, 0xbe, 0xc5, 0xa0, 0xd7,
	0x31, 0x4e, 0x77, 0xed, 0xf2, 0x99, 0x81, 0x68, 0x90, 0xdb, 0xf9, 0xbb, 0xd0, 0x39, 0xa1, 0x2c,
	0x3e, 0x9a, 0x9c, 0xc6, 0x39, 0x0e, 0xae, 0x6d, 0x4d, 0xff, 0xf7, 0x3a, 0xdc, 0xc9, 0x73, 0x7e,
	0x43, 0xa5, 0x2a, 0x41, 0x66, 0xde, 0x42, 0xdf, 0x87, 0x4d, 0xce, 0x92, 0x49, 0xf8, 0x81, 0xaa,
	0x51, 0x88, 0x87, 0x82, 0x10, 0x3d, 0xcb, 0x06, 0x28, 0x2b, 0xc1, 0x86, 0x56, 0xfd, 0x40, 0xd5,
	0xe8, 0x65, 0xae, 0x40, 0x8f, 0x61, 0x2b, 0xc1, 0x52, 0x85, 0x63, 0x3c, 0xe1, 0x99, 0x0a, 0x63,
	0xac, 0x48, 0x68, 0x66, 0x54, 0x63, 0x67, 0x31, 0x40, 0x5a, 0x79, 0x6e, 0x74, 0xaf, 0xb0, 0x22,
	0x27, 0x7a, 0x62, 0xf7, 0x60, 0x73, 0xc6, 0x45, 0x71, 0x03, 0xa6, 0xc5, 0xe0, 0x56, 0xd5, 0xe1,
	0x3b, 0x8e, 0x3e, 0x03, 0x54, 0x36, 0xc7, 0xa9, 0x79, 0x01, 0x96, 0xcc, 0x1c, 0x97, 0xac, 0x5f,
	0x1a, 0xb9, 0xae, 0x49, 0x72, 0xa1, 0xcc, 0xea, 0x6d, 0x05, 0x86, 0xd6, 0xd8, 0x4a, 0x68, 0x4a,
	0x95, 0xc1, 0xd6, 0x52, 0x60, 0x19, 0xbd, 0x90, 0xf8, 0x60, 0x20, 0x89, 0x32, 0xf0, 0x5a, 0x0a,
	0x1c, 0xe7, 0xbf, 0x80, 0x56, 0xde, 0x2f, 0x89, 0x0e, 0xa0, 0x95, 0xe6, 0x8c, 0xfb, 0xb0, 0xd8,
	0x98, 0xb9, 0xca, 0x60, 0x6a, 0xe3, 0xf7, 0x60, 0xbb, 0xb8, 0xe1, 0x11, 0x66, 0x43, 0x72, 0x61,
	0xd6, 0xdc, 0x0d, 0xb7, 0x53, 0xda, 0x8a, 0xf5, 0xf2, 0x56, 0x7c, 0xf2, 0x47, 0x13, 0xda, 0x47,
	0x36, 0xcd, 0x05, 0x11, 0x57, 0x34, 0x22, 0xe8, 0x18, 0xd0, 0x3b, 0xbd, 0x9c, 0xed, 0x97, 0xc6,
	0xb9, 0xe0, 0xe6, 0x7d, 0xdd, 0x2e, 0x4e, 0x53, 0x52, 0xba, 0x6c, 0xdd, 0x76, 0x55, 0xe9, 0x2f,
	0xa0, 0xe8, 0xa6, 0x17, 0xde, 0x04, 0xbb, 0xf9, 0xb5, 0xcb, 0x23, 0xee, 0x7e, 0xc2, 0xc2, 0x7d,
	0x9f, 0x2d, 0xa0, 0x6f, 0xaf, 0x7d, 0xa0, 0xe5, 0xe1, 0xbb, 0x37, 0x7f, 0x92, 0x75, 0xb7, 0xe7,
	0xea, 0x8a, 0x90, 0x17, 0x70, 0x27, 0x57, 0xe1, 0x24, 0xe9, 0xe3, 0xe8, 0x72, 0x7e, 0xd0, 0xca,
	0xfb, 0x76, 0x2d, 0x68, 0xf5, 0x41, 0xf2, 0x17, 0xd0, 0x17, 0xb0, 0x16, 0x90, 0x7e, 0x46, 0x93,
	0xf8, 0x18, 0x47, 0x23, 0x82, 0x90, 0x35, 0x2f, 0x7f, 0x7e, 0x76, 0x37, 0x2b, 0xb2, 0xc2, 0xf5,
	0x29, 0xac, 0xbe, 0x1f, 0x6b, 0xe4, 0x9a, 0xc6, 0xa2, 0x6b, 0x8d, 0xbe, 0xc9, 0xeb, 0x10, 0xda,
	0xd6, 0x2b, 0x87, 0x08, 0x9a, 0x05, 0xd3, 0x4d, 0xbe, 0xaf, 0xa1, 0xfd, 0x9a, 0xa8, 0xd2, 0xd3,
	0x86, 0x3c, 0x6b, 0x38, 0xfb, 0x4e, 0x76, 0xef, 0xcd, 0xd1, 0x14, 0x81, 0xbe, 0x84, 0xce, 0x6b,
	0xa2, 0xf2, 0x74, 0x7a, 0x75, 0xa0, 0x2d, 0x6b, 0x7f, 0x6d, 0x95, 0x74, 0x67, 0x0f, 0xe7, 0x2f,
	0xa0, 0x1e, 0xdc, 0xad, 0xb8, 0xf7, 0xa6, 0x2f, 0xcc, 0x7f, 0x09, 0xf3, 0x35, 0xac, 0xeb, 0x6d,
	0x34, 0x9d, 0xb4, 0xfb, 0xd6, 0x79, 0xfe, 0xaa, 0xea, 0x76, 0xaa, 0x5a, 0xe9, 0x2f, 0xa0, 0xaf,
	0xa0, 0x6d, 0x27, 0xac, 0x68, 0xe6, 0xcc, 0xbe, 0xfc, 0xe4, 0x09, 0xce, 0xe0, 0x76, 0xd5, 0xff,
	0xc2, 0x7d, 0xa2, 0x57, 0x53, 0xcd, 0x99, 0xe2, 0xb9, 0xf1, 0x8e, 0x5e, 0xfc, 0x78, 0x38, 0xa4,
	0x6a, 0x94, 0xf5, 0xf7, 0x23, 0x9e, 0x1e, 0x8c, 0xf1, 0x44, 0x66, 0x63, 0x22, 0x0a, 0x62, 0xcf,
	0xb9, 0xec, 0x49, 0x22, 0xae, 0xb4, 0xfc, 0x72, 0x78, 0x60, 0x7e, 0xf1, 0x98, 0x5f, 0x46, 0xfd,
	0x65, 0x43, 0x7f, 0xfe, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xc4, 0x02, 0xb1, 0x2d, 0x0d,
	0x00, 0x00,
}
