// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/grpc.proto

package grpc // import "github.com/ProtocolONE/payone-billing-service/pkg/proto/grpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/ProtocolONE/payone-billing-service/pkg/proto/billing"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_34ea6026989148e2, []int{0}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_34ea6026989148e2, []int{1}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "grpc.EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "grpc.EmptyResponse")
}

func init() { proto.RegisterFile("grpc/grpc.proto", fileDescriptor_grpc_34ea6026989148e2) }

var fileDescriptor_grpc_34ea6026989148e2 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x6b, 0xc4, 0x20,
	0x1c, 0xc5, 0xaf, 0x50, 0x3a, 0xc8, 0x35, 0x07, 0x96, 0x2e, 0xe9, 0xe6, 0x7e, 0x0a, 0xed, 0x54,
	0x28, 0x1d, 0x2e, 0xdc, 0xda, 0x0b, 0xe9, 0xd6, 0x2d, 0x9a, 0x3f, 0x46, 0x6a, 0xa2, 0x55, 0x53,
	0xc8, 0xb7, 0xe8, 0x47, 0x2e, 0x51, 0x0f, 0x92, 0x45, 0x9f, 0x3e, 0x7c, 0xfe, 0xde, 0x1f, 0x1d,
	0xa4, 0xb3, 0x82, 0x2d, 0x0b, 0xb5, 0xce, 0x04, 0x83, 0x6f, 0x17, 0x5d, 0x3e, 0x72, 0xa5, 0xb5,
	0x1a, 0x25, 0xcb, 0x7b, 0x32, 0x49, 0x81, 0xf6, 0xe7, 0xc1, 0x86, 0xb9, 0x81, 0x9f, 0x09, 0x7c,
	0x20, 0x07, 0x74, 0x9f, 0xcf, 0xde, 0x9a, 0xd1, 0xc3, 0xf3, 0xdf, 0x0d, 0x2a, 0x4e, 0xe9, 0xc9,
	0x27, 0xb8, 0x5f, 0x25, 0x00, 0x57, 0x08, 0x5f, 0x5c, 0x07, 0xae, 0x72, 0xd0, 0x06, 0xa8, 0x9d,
	0x11, 0xe0, 0x3d, 0x7e, 0xa2, 0xd7, 0xe4, 0x95, 0x99, 0x63, 0xcb, 0x62, 0x6b, 0x92, 0x1d, 0x7e,
	0x45, 0xfb, 0x06, 0xf8, 0xa4, 0x74, 0x57, 0xb5, 0xa2, 0x07, 0x8c, 0x69, 0x44, 0x5e, 0xc3, 0x94,
	0x0f, 0x9b, 0xbb, 0x04, 0x44, 0x76, 0xa7, 0xf7, 0xaf, 0x37, 0xa9, 0x42, 0x3f, 0x71, 0x2a, 0xcc,
	0xc0, 0xea, 0xa5, 0x87, 0x30, 0xfa, 0xf2, 0x71, 0x66, 0xb6, 0x9d, 0xcd, 0x08, 0xc7, 0xfc, 0xd7,
	0xd1, 0x27, 0x60, 0x66, 0xbf, 0x25, 0x8b, 0x75, 0xe3, 0x58, 0xf8, 0x5d, 0xd4, 0x2f, 0xff, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xdf, 0x7f, 0xf8, 0x07, 0x2a, 0x01, 0x00, 0x00,
}
