// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billing/billing.proto

package billing // import "github.com/ProtocolONE/payone-billing-service/pkg/proto/billing"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Name struct {
	// @inject_tag: bson:"EN" json:"EN" structure:"EN"
	En string `protobuf:"bytes,1,opt,name=en,proto3" json:"EN" bson:"EN" structure:"EN"`
	// @inject_tag: bson:"RU" json:"RU" structure:"RU"
	Ru                   string   `protobuf:"bytes,2,opt,name=ru,proto3" json:"RU" bson:"RU" structure:"RU"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{0}
}
func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (dst *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(dst, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *Name) GetRu() string {
	if m != nil {
		return m.Ru
	}
	return ""
}

type OrderCreateRequest struct {
	// @inject_tag: query:"PO_PROJECT_ID" form:"PO_PROJECT_ID" json:"project" validate:"required,hexadecimal"
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project" query:"PO_PROJECT_ID" form:"PO_PROJECT_ID" validate:"required,hexadecimal"`
	// @inject_tag: query:"PO_SIGNATURE" form:"PO_SIGNATURE" json:"signature" validate:"omitempty,alphanum"
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature" query:"PO_SIGNATURE" form:"PO_SIGNATURE" validate:"omitempty,alphanum"`
	// @inject_tag: query:"PO_AMOUNT" form:"PO_AMOUNT" json:"amount" validate:"required,numeric"
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount" query:"PO_AMOUNT" form:"PO_AMOUNT" validate:"required,numeric"`
	// @inject_tag: query:"PO_CURRENCY" form:"PO_CURRENCY" json:"currency" validate:"omitempty,alpha,len=3"
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency" query:"PO_CURRENCY" form:"PO_CURRENCY" validate:"omitempty,alpha,len=3"`
	// @inject_tag: "PO_ACCOUNT" form:"PO_ACCOUNT" json:"account"` validate:"omitempty,len=255"
	Account string `protobuf:"bytes,5,opt,name=account,proto3" json:"account" form:"PO_ACCOUNT" validate:"omitempty,len=255"`
	// @inject_tag: query:"PO_ORDER_ID" form:"PO_ORDER_ID" json:"order_id" validate:"omitempty,len=255"
	OrderId string `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id" query:"PO_ORDER_ID" form:"PO_ORDER_ID" validate:"omitempty,len=255"`
	// @inject_tag: query:"PO_DESCRIPTION" form:"PO_DESCRIPTION" json:"description" validate:"omitempty,len=255"
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description" query:"PO_DESCRIPTION" form:"PO_DESCRIPTION" validate:"omitempty,len=255"`
	// @inject_tag: query:"PO_PAYMENT_METHOD" form:"PO_PAYMENT_METHOD" json:"payment_method" validate:"omitempty,len=255"
	PaymentMethod string `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method" query:"PO_PAYMENT_METHOD" form:"PO_PAYMENT_METHOD" validate:"omitempty,len=255"`
	// @inject_tag: query:"PO_URL_VERIFY" form:"PO_URL_VERIFY" json:"url_verify" validate:"omitempty,url"
	UrlVerify string `protobuf:"bytes,9,opt,name=url_verify,json=urlVerify,proto3" json:"url_verify" query:"PO_URL_VERIFY" form:"PO_URL_VERIFY" validate:"omitempty,url"`
	// @inject_tag: query:"PO_URL_NOTIFY" form:"PO_URL_NOTIFY" json:"url_notify" validate:"omitempty,url"
	UrlNotify string `protobuf:"bytes,10,opt,name=url_notify,json=urlNotify,proto3" json:"url_notify" query:"PO_URL_NOTIFY" form:"PO_URL_NOTIFY" validate:"omitempty,url"`
	// @inject_tag: query:"PO_URL_SUCCESS" form:"PO_URL_SUCCESS" json:"url_success" validate:"omitempty,url"
	UrlSuccess string `protobuf:"bytes,11,opt,name=url_success,json=urlSuccess,proto3" json:"url_success" query:"PO_URL_SUCCESS" form:"PO_URL_SUCCESS" validate:"omitempty,url"`
	// @inject_tag: query:"PP_URL_FAIL" form:"PP_URL_FAIL" json:"url_fail" validate:"omitempty,url"
	UrlFail string `protobuf:"bytes,12,opt,name=url_fail,json=urlFail,proto3" json:"url_fail" query:"PP_URL_FAIL" form:"PP_URL_FAIL" validate:"omitempty,url"`
	// @inject_tag: query:"PP_PAYER_EMAIL" form:"PP_PAYER_EMAIL" json:"payer_email" validate:"omitempty,email"
	PayerEmail string `protobuf:"bytes,13,opt,name=payer_email,json=payerEmail,proto3" json:"payer_email" query:"PP_PAYER_EMAIL" form:"PP_PAYER_EMAIL" validate:"omitempty,email"`
	// @inject_tag: query:"PP_PAYER_PHONE" form:"PP_PAYER_PHONE" json:"payer_phone" validate:"omitempty,len=255"
	PayerPhone string `protobuf:"bytes,14,opt,name=payer_phone,json=payerPhone,proto3" json:"payer_phone" query:"PP_PAYER_PHONE" form:"PP_PAYER_PHONE" validate:"omitempty,len=255"`
	// @inject_tag: query:"PP_REGION" form:"PP_REGION" json:"region" validate:"omitempty,alpha,len=2"
	Region  string            `protobuf:"bytes,15,opt,name=region,proto3" json:"region" query:"PP_REGION" form:"PP_REGION" validate:"omitempty,alpha,len=2"`
	PayerIp string            `protobuf:"bytes,16,opt,name=payer_ip,json=payerIp,proto3" json:"payer_ip,omitempty"`
	Other   map[string]string `protobuf:"bytes,17,rep,name=other,proto3" json:"other,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// @inject_tag: json:"-"
	RawParams map[string]string `protobuf:"bytes,18,rep,name=raw_params,json=rawParams,proto3" json:"-" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// @inject_tag: json:"-"
	RawBody string `protobuf:"bytes,19,opt,name=raw_body,json=rawBody,proto3" json:"-"`
	// @inject_tag: json:"-"
	IsJson               bool     `protobuf:"varint,20,opt,name=is_json,json=isJson,proto3" json:"-"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *OrderCreateRequest) Reset()         { *m = OrderCreateRequest{} }
func (m *OrderCreateRequest) String() string { return proto.CompactTextString(m) }
func (*OrderCreateRequest) ProtoMessage()    {}
func (*OrderCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{1}
}
func (m *OrderCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCreateRequest.Unmarshal(m, b)
}
func (m *OrderCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCreateRequest.Marshal(b, m, deterministic)
}
func (dst *OrderCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCreateRequest.Merge(dst, src)
}
func (m *OrderCreateRequest) XXX_Size() int {
	return xxx_messageInfo_OrderCreateRequest.Size(m)
}
func (m *OrderCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCreateRequest proto.InternalMessageInfo

func (m *OrderCreateRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *OrderCreateRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *OrderCreateRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *OrderCreateRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *OrderCreateRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *OrderCreateRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderCreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *OrderCreateRequest) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *OrderCreateRequest) GetUrlVerify() string {
	if m != nil {
		return m.UrlVerify
	}
	return ""
}

func (m *OrderCreateRequest) GetUrlNotify() string {
	if m != nil {
		return m.UrlNotify
	}
	return ""
}

func (m *OrderCreateRequest) GetUrlSuccess() string {
	if m != nil {
		return m.UrlSuccess
	}
	return ""
}

func (m *OrderCreateRequest) GetUrlFail() string {
	if m != nil {
		return m.UrlFail
	}
	return ""
}

func (m *OrderCreateRequest) GetPayerEmail() string {
	if m != nil {
		return m.PayerEmail
	}
	return ""
}

func (m *OrderCreateRequest) GetPayerPhone() string {
	if m != nil {
		return m.PayerPhone
	}
	return ""
}

func (m *OrderCreateRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *OrderCreateRequest) GetPayerIp() string {
	if m != nil {
		return m.PayerIp
	}
	return ""
}

func (m *OrderCreateRequest) GetOther() map[string]string {
	if m != nil {
		return m.Other
	}
	return nil
}

func (m *OrderCreateRequest) GetRawParams() map[string]string {
	if m != nil {
		return m.RawParams
	}
	return nil
}

func (m *OrderCreateRequest) GetRawBody() string {
	if m != nil {
		return m.RawBody
	}
	return ""
}

func (m *OrderCreateRequest) GetIsJson() bool {
	if m != nil {
		return m.IsJson
	}
	return false
}

type Project struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	// @inject_tag: bson:"callback_currency" structure:"callback_currency"
	CallbackCurrency *Currency `protobuf:"bytes,2,opt,name=callback_currency,json=callbackCurrency,proto3" json:"callback_currency,omitempty" bson:"callback_currency" structure:"callback_currency"`
	// @inject_tag: bson:"callback_protocol" structure:"callback_protocol"
	CallbackProtocol string `protobuf:"bytes,3,opt,name=callback_protocol,json=callbackProtocol,proto3" json:"callback_protocol,omitempty" bson:"callback_protocol" structure:"callback_protocol"`
	// @inject_tag: bson:"create_invoice_allowed_urls" structure:"create_invoice_allowed_urls"
	CreateInvoiceAllowedUrls []string `protobuf:"bytes,4,rep,name=create_invoice_allowed_urls,json=createInvoiceAllowedUrls,proto3" json:"create_invoice_allowed_urls,omitempty" bson:"create_invoice_allowed_urls" structure:"create_invoice_allowed_urls"`
	// @inject_tag: bson:"merchant" json:"-" structure:"merchant"
	Merchant *Merchant `protobuf:"bytes,5,opt,name=merchant,proto3" json:"-" bson:"merchant" structure:"merchant"`
	// @inject_tag: bson:"is_allow_dynamic_notify_urls" structure:"is_allow_dynamic_notify_urls"
	IsAllowDynamicNotifyUrls bool `protobuf:"varint,6,opt,name=is_allow_dynamic_notify_urls,json=isAllowDynamicNotifyUrls,proto3" json:"is_allow_dynamic_notify_urls,omitempty" bson:"is_allow_dynamic_notify_urls" structure:"is_allow_dynamic_notify_urls"`
	// @inject_tag: bson:"is_allow_dynamic_redirect_urls" structure:"is_allow_dynamic_redirect_urls"
	IsAllowDynamicRedirectUrls bool `protobuf:"varint,7,opt,name=is_allow_dynamic_redirect_urls,json=isAllowDynamicRedirectUrls,proto3" json:"is_allow_dynamic_redirect_urls,omitempty" bson:"is_allow_dynamic_redirect_urls" structure:"is_allow_dynamic_redirect_urls"`
	// @inject_tag: bson:"limits_currency" structure:"limits_currency"
	LimitsCurrency *Currency `protobuf:"bytes,8,opt,name=limits_currency,json=limitsCurrency,proto3" json:"limits_currency,omitempty" bson:"limits_currency" structure:"limits_currency"`
	// @inject_tag: bson:"max_payment_amount" structure:"max_payment_amount"
	MaxPaymentAmount float64 `protobuf:"fixed64,9,opt,name=max_payment_amount,json=maxPaymentAmount,proto3" json:"max_payment_amount,omitempty" bson:"max_payment_amount" structure:"max_payment_amount"`
	// @inject_tag: bson:"min_payment_amount" structure:"min_payment_amount"
	MinPaymentAmount float64 `protobuf:"fixed64,10,opt,name=min_payment_amount,json=minPaymentAmount,proto3" json:"min_payment_amount,omitempty" bson:"min_payment_amount" structure:"min_payment_amount"`
	// @inject_tag: bson:"name" structure:"name"
	Name string `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty" bson:"name" structure:"name"`
	// @inject_tag: bson:"notify_emails" structure:"notify_emails"
	NotifyEmails []string `protobuf:"bytes,12,rep,name=notify_emails,json=notifyEmails,proto3" json:"notify_emails,omitempty" bson:"notify_emails" structure:"notify_emails"`
	// @inject_tag: bson:"only_fixed_amounts" structure:"only_fixed_amounts"
	OnlyFixedAmounts bool `protobuf:"varint,13,opt,name=only_fixed_amounts,json=onlyFixedAmounts,proto3" json:"only_fixed_amounts,omitempty" bson:"only_fixed_amounts" structure:"only_fixed_amounts"`
	// @inject_tag: bson:"secret_key" structure:"secret_key"
	SecretKey string `protobuf:"bytes,14,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty" bson:"secret_key" structure:"secret_key"`
	// @inject_tag: bson:"send_notify_email" structure:"send_notify_email"
	SendNotifyEmail bool `protobuf:"varint,15,opt,name=send_notify_email,json=sendNotifyEmail,proto3" json:"send_notify_email,omitempty" bson:"send_notify_email" structure:"send_notify_email"`
	// @inject_tag: bson:"url_check_account" structure:"url_check_account"
	UrlCheckAccount string `protobuf:"bytes,16,opt,name=url_check_account,json=urlCheckAccount,proto3" json:"url_check_account,omitempty" bson:"url_check_account" structure:"url_check_account"`
	// @inject_tag: bson:"url_process_payment" structure:"url_process_payment"
	UrlProcessPayment string `protobuf:"bytes,17,opt,name=url_process_payment,json=urlProcessPayment,proto3" json:"url_process_payment,omitempty" bson:"url_process_payment" structure:"url_process_payment"`
	// @inject_tag: bson:"url_redirect_fail" structure:"url_redirect_fail"
	UrlRedirectFail string `protobuf:"bytes,18,opt,name=url_redirect_fail,json=urlRedirectFail,proto3" json:"url_redirect_fail,omitempty" bson:"url_redirect_fail" structure:"url_redirect_fail"`
	// @inject_tag: bson:"url_redirect_success" structure:"url_redirect_success"
	UrlRedirectSuccess string `protobuf:"bytes,19,opt,name=url_redirect_success,json=urlRedirectSuccess,proto3" json:"url_redirect_success,omitempty" bson:"url_redirect_success" structure:"url_redirect_success"`
	// @inject_tag: bson:"fixed_package" structure:"fixed_package"
	FixedPackage map[string]*FixedPackages `protobuf:"bytes,23,rep,name=fixed_package,json=fixedPackage,proto3" json:"fixed_package,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"fixed_package" structure:"fixed_package"`
	// @inject_tag: bson:"payment_methods" structure:"payment_methods"
	PaymentMethods map[string]*ProjectPaymentMethods `protobuf:"bytes,24,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"payment_methods" structure:"payment_methods"`
	// @inject_tag: bson:"is_active" structure:"is_active"
	IsActive             bool     `protobuf:"varint,20,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active" structure:"is_active"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{2}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetCallbackCurrency() *Currency {
	if m != nil {
		return m.CallbackCurrency
	}
	return nil
}

func (m *Project) GetCallbackProtocol() string {
	if m != nil {
		return m.CallbackProtocol
	}
	return ""
}

func (m *Project) GetCreateInvoiceAllowedUrls() []string {
	if m != nil {
		return m.CreateInvoiceAllowedUrls
	}
	return nil
}

func (m *Project) GetMerchant() *Merchant {
	if m != nil {
		return m.Merchant
	}
	return nil
}

func (m *Project) GetIsAllowDynamicNotifyUrls() bool {
	if m != nil {
		return m.IsAllowDynamicNotifyUrls
	}
	return false
}

func (m *Project) GetIsAllowDynamicRedirectUrls() bool {
	if m != nil {
		return m.IsAllowDynamicRedirectUrls
	}
	return false
}

func (m *Project) GetLimitsCurrency() *Currency {
	if m != nil {
		return m.LimitsCurrency
	}
	return nil
}

func (m *Project) GetMaxPaymentAmount() float64 {
	if m != nil {
		return m.MaxPaymentAmount
	}
	return 0
}

func (m *Project) GetMinPaymentAmount() float64 {
	if m != nil {
		return m.MinPaymentAmount
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetNotifyEmails() []string {
	if m != nil {
		return m.NotifyEmails
	}
	return nil
}

func (m *Project) GetOnlyFixedAmounts() bool {
	if m != nil {
		return m.OnlyFixedAmounts
	}
	return false
}

func (m *Project) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *Project) GetSendNotifyEmail() bool {
	if m != nil {
		return m.SendNotifyEmail
	}
	return false
}

func (m *Project) GetUrlCheckAccount() string {
	if m != nil {
		return m.UrlCheckAccount
	}
	return ""
}

func (m *Project) GetUrlProcessPayment() string {
	if m != nil {
		return m.UrlProcessPayment
	}
	return ""
}

func (m *Project) GetUrlRedirectFail() string {
	if m != nil {
		return m.UrlRedirectFail
	}
	return ""
}

func (m *Project) GetUrlRedirectSuccess() string {
	if m != nil {
		return m.UrlRedirectSuccess
	}
	return ""
}

func (m *Project) GetFixedPackage() map[string]*FixedPackages {
	if m != nil {
		return m.FixedPackage
	}
	return nil
}

func (m *Project) GetPaymentMethods() map[string]*ProjectPaymentMethods {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

func (m *Project) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type ProjectOrder struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	// @inject_tag: bson:"name" structure:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name" structure:"name"`
	// @inject_tag: bson:"url_redirect_success" structure:"url_redirect_success"
	UrlSuccess string `protobuf:"bytes,3,opt,name=url_success,json=urlSuccess,proto3" json:"url_success,omitempty" bson:"url_redirect_success" structure:"url_redirect_success"`
	// @inject_tag: bson:"url_redirect_fail" structure:"url_redirect_fail"
	UrlFail string `protobuf:"bytes,4,opt,name=url_fail,json=urlFail,proto3" json:"url_fail,omitempty" bson:"url_redirect_fail" structure:"url_redirect_fail"`
	// @inject_tag: bson:"notify_emails" structure:"notify_emails"
	NotifyEmails []string `protobuf:"bytes,5,rep,name=notify_emails,json=notifyEmails,proto3" json:"notify_emails,omitempty" bson:"notify_emails" structure:"notify_emails"`
	// @inject_tag: bson:"secret_key" structure:"secret_key"
	SecretKey string `protobuf:"bytes,6,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty" bson:"secret_key" structure:"secret_key"`
	// @inject_tag: bson:"send_notify_email" structure:"send_notify_email"
	SendNotifyEmail bool `protobuf:"varint,7,opt,name=send_notify_email,json=sendNotifyEmail,proto3" json:"send_notify_email,omitempty" bson:"send_notify_email" structure:"send_notify_email"`
	// @inject_tag: bson:"url_check_account" structure:"url_check_account"
	UrlCheckAccount string `protobuf:"bytes,8,opt,name=url_check_account,json=urlCheckAccount,proto3" json:"url_check_account,omitempty" bson:"url_check_account" structure:"url_check_account"`
	// @inject_tag: bson:"url_process_payment" structure:"url_process_payment"
	UrlProcessPayment string `protobuf:"bytes,9,opt,name=url_process_payment,json=urlProcessPayment,proto3" json:"url_process_payment,omitempty" bson:"url_process_payment" structure:"url_process_payment"`
	// @inject_tag: bson:"callback_protocol" structure:"callback_protocol"
	CallbackProtocol string `protobuf:"bytes,10,opt,name=callback_protocol,json=callbackProtocol,proto3" json:"callback_protocol,omitempty" bson:"callback_protocol" structure:"callback_protocol"`
	// @inject_tag: bson:"merchant" structure:"merchant"
	Merchant             *Merchant `protobuf:"bytes,12,opt,name=merchant,proto3" json:"merchant,omitempty" bson:"merchant" structure:"merchant"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-" structure:"-"`
}

func (m *ProjectOrder) Reset()         { *m = ProjectOrder{} }
func (m *ProjectOrder) String() string { return proto.CompactTextString(m) }
func (*ProjectOrder) ProtoMessage()    {}
func (*ProjectOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{3}
}
func (m *ProjectOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectOrder.Unmarshal(m, b)
}
func (m *ProjectOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectOrder.Marshal(b, m, deterministic)
}
func (dst *ProjectOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectOrder.Merge(dst, src)
}
func (m *ProjectOrder) XXX_Size() int {
	return xxx_messageInfo_ProjectOrder.Size(m)
}
func (m *ProjectOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectOrder proto.InternalMessageInfo

func (m *ProjectOrder) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ProjectOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectOrder) GetUrlSuccess() string {
	if m != nil {
		return m.UrlSuccess
	}
	return ""
}

func (m *ProjectOrder) GetUrlFail() string {
	if m != nil {
		return m.UrlFail
	}
	return ""
}

func (m *ProjectOrder) GetNotifyEmails() []string {
	if m != nil {
		return m.NotifyEmails
	}
	return nil
}

func (m *ProjectOrder) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *ProjectOrder) GetSendNotifyEmail() bool {
	if m != nil {
		return m.SendNotifyEmail
	}
	return false
}

func (m *ProjectOrder) GetUrlCheckAccount() string {
	if m != nil {
		return m.UrlCheckAccount
	}
	return ""
}

func (m *ProjectOrder) GetUrlProcessPayment() string {
	if m != nil {
		return m.UrlProcessPayment
	}
	return ""
}

func (m *ProjectOrder) GetCallbackProtocol() string {
	if m != nil {
		return m.CallbackProtocol
	}
	return ""
}

func (m *ProjectOrder) GetMerchant() *Merchant {
	if m != nil {
		return m.Merchant
	}
	return nil
}

type Merchant struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	// @inject_tag: bson:"external_id" structure:"external_id"
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty" bson:"external_id" structure:"external_id"`
	// @inject_tag: bson:"currency" structure:"currency"
	Currency *Currency `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty" bson:"currency" structure:"currency"`
	// @inject_tag: bson:"is_vat_enabled" structure:"is_vat_enabled"
	IsVatEnabled bool `protobuf:"varint,4,opt,name=is_vat_enabled,json=isVatEnabled,proto3" json:"is_vat_enabled,omitempty" bson:"is_vat_enabled" structure:"is_vat_enabled"`
	// @inject_tag: bson:"is_commission_to_user_enabled" structure:"is_commission_to_user_enabled"
	IsCommissionToUserEnabled bool `protobuf:"varint,5,opt,name=is_commission_to_user_enabled,json=isCommissionToUserEnabled,proto3" json:"is_commission_to_user_enabled,omitempty" bson:"is_commission_to_user_enabled" structure:"is_commission_to_user_enabled"`
	// @inject_tag: bson:"status" structure:"status"
	Status int32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty" bson:"status" structure:"status"`
	// @inject_tag: bson:"first_payment_at" structure:"first_payment_at,timestamp"
	FirstPaymentAt       *timestamp.Timestamp `protobuf:"bytes,7,opt,name=first_payment_at,json=firstPaymentAt,proto3" json:"first_payment_at,omitempty" bson:"first_payment_at" structure:"first_payment_at,timestamp"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{4}
}
func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Merchant.Unmarshal(m, b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
}
func (dst *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(dst, src)
}
func (m *Merchant) XXX_Size() int {
	return xxx_messageInfo_Merchant.Size(m)
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Merchant) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Merchant) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *Merchant) GetIsVatEnabled() bool {
	if m != nil {
		return m.IsVatEnabled
	}
	return false
}

func (m *Merchant) GetIsCommissionToUserEnabled() bool {
	if m != nil {
		return m.IsCommissionToUserEnabled
	}
	return false
}

func (m *Merchant) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Merchant) GetFirstPaymentAt() *timestamp.Timestamp {
	if m != nil {
		return m.FirstPaymentAt
	}
	return nil
}

type Order struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	// @inject_tag: bson:"project" structure:"project"
	Project *ProjectOrder `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty" bson:"project" structure:"project"`
	// @inject_tag: bson:"project_order_id" structure:"project_order_id"
	ProjectOrderId string `protobuf:"bytes,3,opt,name=project_order_id,json=projectOrderId,proto3" json:"project_order_id,omitempty" bson:"project_order_id" structure:"project_order_id"`
	// @inject_tag: bson:"project_account" structure:"project_account"
	ProjectAccount string `protobuf:"bytes,4,opt,name=project_account,json=projectAccount,proto3" json:"project_account,omitempty" bson:"project_account" structure:"project_account"`
	// @inject_tag: bson:"description" structure:"description"
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty" bson:"description" structure:"description"`
	// @inject_tag: bson:"project_income_amount" structure:"project_income_amount"
	ProjectIncomeAmount float64 `protobuf:"fixed64,6,opt,name=project_income_amount,json=projectIncomeAmount,proto3" json:"project_income_amount,omitempty" bson:"project_income_amount" structure:"project_income_amount"`
	// @inject_tag: bson:"project_income_currency" structure:"project_income_currency"
	ProjectIncomeCurrency *Currency `protobuf:"bytes,7,opt,name=project_income_currency,json=projectIncomeCurrency,proto3" json:"project_income_currency,omitempty" bson:"project_income_currency" structure:"project_income_currency"`
	// @inject_tag: bson:"project_outcome_amount" structure:"project_outcome_amount"
	ProjectOutcomeAmount float64 `protobuf:"fixed64,8,opt,name=project_outcome_amount,json=projectOutcomeAmount,proto3" json:"project_outcome_amount,omitempty" bson:"project_outcome_amount" structure:"project_outcome_amount"`
	// @inject_tag: bson:"project_outcome_currency" structure:"project_outcome_currency"
	ProjectOutcomeCurrency *Currency `protobuf:"bytes,9,opt,name=project_outcome_currency,json=projectOutcomeCurrency,proto3" json:"project_outcome_currency,omitempty" bson:"project_outcome_currency" structure:"project_outcome_currency"`
	// @inject_tag: bson:"project_last_requested_at" structure:"project_last_requested_at,timestamp"
	ProjectLastRequestedAt *timestamp.Timestamp `protobuf:"bytes,10,opt,name=project_last_requested_at,json=projectLastRequestedAt,proto3" json:"project_last_requested_at,omitempty" bson:"project_last_requested_at" structure:"project_last_requested_at,timestamp"`
	// @inject_tag: bson:"project_params" structure:"project_params"
	ProjectParams map[string]string `protobuf:"bytes,11,rep,name=project_params,json=projectParams,proto3" json:"project_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"project_params" structure:"project_params"`
	// @inject_tag: bson:"payer_data" structure:"payer_data"
	PayerData *PayerData `protobuf:"bytes,12,opt,name=payer_data,json=payerData,proto3" json:"payer_data,omitempty" bson:"payer_data" structure:"payer_data"`
	// @inject_tag: bson:"payment_method" structure:"payment_method"
	PaymentMethod *PaymentMethodOrder `protobuf:"bytes,13,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty" bson:"payment_method" structure:"payment_method"`
	// @inject_tag: bson:"pm_terminal_id" structure:"pm_terminal_id"
	PaymentMethodTerminalId string `protobuf:"bytes,14,opt,name=payment_method_terminal_id,json=paymentMethodTerminalId,proto3" json:"payment_method_terminal_id,omitempty" bson:"pm_terminal_id" structure:"pm_terminal_id"`
	// @inject_tag: bson:"pm_order_id" structure:"pm_order_id"
	PaymentMethodOrderId string `protobuf:"bytes,15,opt,name=payment_method_order_id,json=paymentMethodOrderId,proto3" json:"payment_method_order_id,omitempty" bson:"pm_order_id" structure:"pm_order_id"`
	// @inject_tag: bson:"pm_outcome_amount" structure:"pm_outcome_amount"
	PaymentMethodOutcomeAmount float64 `protobuf:"fixed64,16,opt,name=payment_method_outcome_amount,json=paymentMethodOutcomeAmount,proto3" json:"payment_method_outcome_amount,omitempty" bson:"pm_outcome_amount" structure:"pm_outcome_amount"`
	// @inject_tag: bson:"pm_outcome_currency" structure:"pm_outcome_currency"
	PaymentMethodOutcomeCurrency *Currency `protobuf:"bytes,17,opt,name=payment_method_outcome_currency,json=paymentMethodOutcomeCurrency,proto3" json:"payment_method_outcome_currency,omitempty" bson:"pm_outcome_currency" structure:"pm_outcome_currency"`
	// @inject_tag: bson:"pm_income_amount" structure:"pm_income_amount"
	PaymentMethodIncomeAmount float64 `protobuf:"fixed64,18,opt,name=payment_method_income_amount,json=paymentMethodIncomeAmount,proto3" json:"payment_method_income_amount,omitempty" bson:"pm_income_amount" structure:"pm_income_amount"`
	// @inject_tag: bson:"pm_income_currency" structure:"pm_income_currency"
	PaymentMethodIncomeCurrency *Currency `protobuf:"bytes,19,opt,name=payment_method_income_currency,json=paymentMethodIncomeCurrency,proto3" json:"payment_method_income_currency,omitempty" bson:"pm_income_currency" structure:"pm_income_currency"`
	// @inject_tag: bson:"-" json:"-" structure:"-"
	PaymentMethodIncomeCurrencyA3 string `protobuf:"bytes,20,opt,name=payment_method_income_currency_a3,json=paymentMethodIncomeCurrencyA3,proto3" json:"-" bson:"-" structure:"-"`
	// @inject_tag: bson:"pm_order_close_date" structure:"pm_order_close_date,timestamp"
	PaymentMethodOrderClosedAt *timestamp.Timestamp `protobuf:"bytes,21,opt,name=payment_method_order_closed_at,json=paymentMethodOrderClosedAt,proto3" json:"payment_method_order_closed_at,omitempty" bson:"pm_order_close_date" structure:"pm_order_close_date,timestamp"`
	// @inject_tag: bson:"status" structure:"status"
	Status int32 `protobuf:"varint,22,opt,name=status,proto3" json:"status,omitempty" bson:"status" structure:"status"`
	// @inject_tag: bson:"created_at" structure:"created_at,timestamp"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,23,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at" structure:"created_at,timestamp"`
	// @inject_tag: bson:"updated_at" structure:"updated_at,timestamp"
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at" structure:"updated_at,timestamp"`
	// @inject_tag: bson:"created_by_json" structure:"created_by_json"
	IsJsonRequest bool `protobuf:"varint,25,opt,name=is_json_request,json=isJsonRequest,proto3" json:"is_json_request,omitempty" bson:"created_by_json" structure:"created_by_json"`
	// @inject_tag: bson:"amount_psp_ac" structure:"amount_psp_ac"
	AmountInPspAccountingCurrency float64 `protobuf:"fixed64,26,opt,name=amount_in_psp_accounting_currency,json=amountInPspAccountingCurrency,proto3" json:"amount_in_psp_accounting_currency,omitempty" bson:"amount_psp_ac" structure:"amount_psp_ac"`
	// @inject_tag: bson:"amount_in_merchant_ac" structure:"amount_in_merchant_ac"
	AmountInMerchantAccountingCurrency float64 `protobuf:"fixed64,27,opt,name=amount_in_merchant_accounting_currency,json=amountInMerchantAccountingCurrency,proto3" json:"amount_in_merchant_accounting_currency,omitempty" bson:"amount_in_merchant_ac" structure:"amount_in_merchant_ac"`
	// @inject_tag: bson:"amount_out_merchant_ac" structure:"amount_out_merchant_ac"
	AmountOutMerchantAccountingCurrency float64 `protobuf:"fixed64,28,opt,name=amount_out_merchant_accounting_currency,json=amountOutMerchantAccountingCurrency,proto3" json:"amount_out_merchant_accounting_currency,omitempty" bson:"amount_out_merchant_ac" structure:"amount_out_merchant_ac"`
	// @inject_tag: bson:"amount_ps_ac" structure:"amount_ps_ac"
	AmountInPaymentSystemAccountingCurrency float64 `protobuf:"fixed64,29,opt,name=amount_in_payment_system_accounting_currency,json=amountInPaymentSystemAccountingCurrency,proto3" json:"amount_in_payment_system_accounting_currency,omitempty" bson:"amount_ps_ac" structure:"amount_ps_ac"`
	// @inject_tag: bson:"pm_account" structure:"pm_account"
	PaymentMethodPayerAccount string `protobuf:"bytes,30,opt,name=payment_method_payer_account,json=paymentMethodPayerAccount,proto3" json:"payment_method_payer_account,omitempty" bson:"pm_account" structure:"pm_account"`
	// @inject_tag: bson:"pm_txn_params" structure:"pm_txn_params"
	PaymentMethodTxnParams map[string]string `protobuf:"bytes,31,rep,name=payment_method_txn_params,json=paymentMethodTxnParams,proto3" json:"payment_method_txn_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"pm_txn_params" structure:"pm_txn_params"`
	// @inject_tag: bson:"fixed_package" structure:"fixed_package"
	FixedPackage *FixedPackage `protobuf:"bytes,32,opt,name=fixed_package,json=fixedPackage,proto3" json:"fixed_package,omitempty" bson:"fixed_package" structure:"fixed_package"`
	// @inject_tag: bson:"payment_requisites" json:"-" structure:"payment_requisites"
	PaymentRequisites map[string]string `protobuf:"bytes,33,rep,name=payment_requisites,json=paymentRequisites,proto3" json:"-" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"payment_requisites" structure:"payment_requisites"`
	// @inject_tag: bson:"psp_fee_amount" structure:"psp_fee_amount"
	PspFeeAmount *OrderFeePsp `protobuf:"bytes,34,opt,name=psp_fee_amount,json=pspFeeAmount,proto3" json:"psp_fee_amount,omitempty" bson:"psp_fee_amount" structure:"psp_fee_amount"`
	// @inject_tag: bson:"project_fee_amount" structure:"project_fee_amount"
	ProjectFeeAmount *OrderFee `protobuf:"bytes,35,opt,name=project_fee_amount,json=projectFeeAmount,proto3" json:"project_fee_amount,omitempty" bson:"project_fee_amount" structure:"project_fee_amount"`
	// @inject_tag: bson:"to_payer_fee_amount" structure:"to_payer_fee_amount"
	ToPayerFeeAmount *OrderFee `protobuf:"bytes,36,opt,name=to_payer_fee_amount,json=toPayerFeeAmount,proto3" json:"to_payer_fee_amount,omitempty" bson:"to_payer_fee_amount" structure:"to_payer_fee_amount"`
	// @inject_tag: bson:"vat_amount" structure:"vat_amount"
	VatAmount float64 `protobuf:"fixed64,37,opt,name=vat_amount,json=vatAmount,proto3" json:"vat_amount,omitempty" bson:"vat_amount" structure:"vat_amount"`
	// @inject_tag: bson:"ps_fee_amount" structure:"ps_fee_amount"
	PaymentSystemFeeAmount *OrderFeePaymentSystem `protobuf:"bytes,38,opt,name=payment_system_fee_amount,json=paymentSystemFeeAmount,proto3" json:"payment_system_fee_amount,omitempty" bson:"ps_fee_amount" structure:"ps_fee_amount"`
	XXX_NoUnkeyedLiteral   struct{}               `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized       []byte                 `json:"-" bson:"-" structure:"-"`
	XXX_sizecache          int32                  `json:"-" bson:"-" structure:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{5}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetProject() *ProjectOrder {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *Order) GetProjectOrderId() string {
	if m != nil {
		return m.ProjectOrderId
	}
	return ""
}

func (m *Order) GetProjectAccount() string {
	if m != nil {
		return m.ProjectAccount
	}
	return ""
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetProjectIncomeAmount() float64 {
	if m != nil {
		return m.ProjectIncomeAmount
	}
	return 0
}

func (m *Order) GetProjectIncomeCurrency() *Currency {
	if m != nil {
		return m.ProjectIncomeCurrency
	}
	return nil
}

func (m *Order) GetProjectOutcomeAmount() float64 {
	if m != nil {
		return m.ProjectOutcomeAmount
	}
	return 0
}

func (m *Order) GetProjectOutcomeCurrency() *Currency {
	if m != nil {
		return m.ProjectOutcomeCurrency
	}
	return nil
}

func (m *Order) GetProjectLastRequestedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ProjectLastRequestedAt
	}
	return nil
}

func (m *Order) GetProjectParams() map[string]string {
	if m != nil {
		return m.ProjectParams
	}
	return nil
}

func (m *Order) GetPayerData() *PayerData {
	if m != nil {
		return m.PayerData
	}
	return nil
}

func (m *Order) GetPaymentMethod() *PaymentMethodOrder {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

func (m *Order) GetPaymentMethodTerminalId() string {
	if m != nil {
		return m.PaymentMethodTerminalId
	}
	return ""
}

func (m *Order) GetPaymentMethodOrderId() string {
	if m != nil {
		return m.PaymentMethodOrderId
	}
	return ""
}

func (m *Order) GetPaymentMethodOutcomeAmount() float64 {
	if m != nil {
		return m.PaymentMethodOutcomeAmount
	}
	return 0
}

func (m *Order) GetPaymentMethodOutcomeCurrency() *Currency {
	if m != nil {
		return m.PaymentMethodOutcomeCurrency
	}
	return nil
}

func (m *Order) GetPaymentMethodIncomeAmount() float64 {
	if m != nil {
		return m.PaymentMethodIncomeAmount
	}
	return 0
}

func (m *Order) GetPaymentMethodIncomeCurrency() *Currency {
	if m != nil {
		return m.PaymentMethodIncomeCurrency
	}
	return nil
}

func (m *Order) GetPaymentMethodIncomeCurrencyA3() string {
	if m != nil {
		return m.PaymentMethodIncomeCurrencyA3
	}
	return ""
}

func (m *Order) GetPaymentMethodOrderClosedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PaymentMethodOrderClosedAt
	}
	return nil
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetIsJsonRequest() bool {
	if m != nil {
		return m.IsJsonRequest
	}
	return false
}

func (m *Order) GetAmountInPspAccountingCurrency() float64 {
	if m != nil {
		return m.AmountInPspAccountingCurrency
	}
	return 0
}

func (m *Order) GetAmountInMerchantAccountingCurrency() float64 {
	if m != nil {
		return m.AmountInMerchantAccountingCurrency
	}
	return 0
}

func (m *Order) GetAmountOutMerchantAccountingCurrency() float64 {
	if m != nil {
		return m.AmountOutMerchantAccountingCurrency
	}
	return 0
}

func (m *Order) GetAmountInPaymentSystemAccountingCurrency() float64 {
	if m != nil {
		return m.AmountInPaymentSystemAccountingCurrency
	}
	return 0
}

func (m *Order) GetPaymentMethodPayerAccount() string {
	if m != nil {
		return m.PaymentMethodPayerAccount
	}
	return ""
}

func (m *Order) GetPaymentMethodTxnParams() map[string]string {
	if m != nil {
		return m.PaymentMethodTxnParams
	}
	return nil
}

func (m *Order) GetFixedPackage() *FixedPackage {
	if m != nil {
		return m.FixedPackage
	}
	return nil
}

func (m *Order) GetPaymentRequisites() map[string]string {
	if m != nil {
		return m.PaymentRequisites
	}
	return nil
}

func (m *Order) GetPspFeeAmount() *OrderFeePsp {
	if m != nil {
		return m.PspFeeAmount
	}
	return nil
}

func (m *Order) GetProjectFeeAmount() *OrderFee {
	if m != nil {
		return m.ProjectFeeAmount
	}
	return nil
}

func (m *Order) GetToPayerFeeAmount() *OrderFee {
	if m != nil {
		return m.ToPayerFeeAmount
	}
	return nil
}

func (m *Order) GetVatAmount() float64 {
	if m != nil {
		return m.VatAmount
	}
	return 0
}

func (m *Order) GetPaymentSystemFeeAmount() *OrderFeePaymentSystem {
	if m != nil {
		return m.PaymentSystemFeeAmount
	}
	return nil
}

type Currency struct {
	// @inject_tag: bson:"code_int" structure:"code_int"
	CodeInt int32 `protobuf:"varint,1,opt,name=code_int,json=codeInt,proto3" json:"code_int,omitempty" bson:"code_int" structure:"code_int"`
	// @inject_tag: bson:"code_a3" structure:"code_a3"
	CodeA3 string `protobuf:"bytes,2,opt,name=code_a3,json=codeA3,proto3" json:"code_a3,omitempty" bson:"code_a3" structure:"code_a3"`
	// @inject_tag: bson:"is_active" structure:"is_active"
	IsActive             bool     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active" structure:"is_active"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{6}
}
func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (dst *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(dst, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetCodeInt() int32 {
	if m != nil {
		return m.CodeInt
	}
	return 0
}

func (m *Currency) GetCodeA3() string {
	if m != nil {
		return m.CodeA3
	}
	return ""
}

func (m *Currency) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type PayerData struct {
	// @inject_tag: bson:"ip" structure:"ip"
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty" bson:"ip" structure:"ip"`
	// @inject_tag: bson:"country_code_a2" structure:"country_code_a2"
	CountryCodeA2 string `protobuf:"bytes,2,opt,name=country_code_a2,json=countryCodeA2,proto3" json:"country_code_a2,omitempty" bson:"country_code_a2" structure:"country_code_a2"`
	// @inject_tag: bson:"country_name" structure:"country_name"
	CountryName *Name `protobuf:"bytes,3,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty" bson:"country_name" structure:"country_name"`
	// @inject_tag: bson:"city" structure:"city"
	City *Name `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty" bson:"city" structure:"city"`
	// @inject_tag: bson:"subdivision" structure:"subdivision"
	Subdivision string `protobuf:"bytes,5,opt,name=subdivision,proto3" json:"subdivision,omitempty" bson:"subdivision" structure:"subdivision"`
	// @inject_tag: bson:"timezone" structure:"timezone"
	Timezone string `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty" bson:"timezone" structure:"timezone"`
	// @inject_tag: bson:"phone" structure:"phone"
	Phone string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty" bson:"phone" structure:"phone"`
	// @inject_tag: bson:"email" structure:"email"
	Email                string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty" bson:"email" structure:"email"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *PayerData) Reset()         { *m = PayerData{} }
func (m *PayerData) String() string { return proto.CompactTextString(m) }
func (*PayerData) ProtoMessage()    {}
func (*PayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{7}
}
func (m *PayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayerData.Unmarshal(m, b)
}
func (m *PayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayerData.Marshal(b, m, deterministic)
}
func (dst *PayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayerData.Merge(dst, src)
}
func (m *PayerData) XXX_Size() int {
	return xxx_messageInfo_PayerData.Size(m)
}
func (m *PayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PayerData proto.InternalMessageInfo

func (m *PayerData) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PayerData) GetCountryCodeA2() string {
	if m != nil {
		return m.CountryCodeA2
	}
	return ""
}

func (m *PayerData) GetCountryName() *Name {
	if m != nil {
		return m.CountryName
	}
	return nil
}

func (m *PayerData) GetCity() *Name {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *PayerData) GetSubdivision() string {
	if m != nil {
		return m.Subdivision
	}
	return ""
}

func (m *PayerData) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *PayerData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PayerData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type PaymentMethodOrder struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	// @inject_tag: bson:"name" structure:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name" structure:"name"`
	// @inject_tag: bson:"params" structure:"params"
	Params *PaymentMethodParams `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty" bson:"params" structure:"params"`
	// @inject_tag: bson:"payment_system" structure:"payment_system"
	PaymentSystem *PaymentSystem `protobuf:"bytes,4,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty" bson:"payment_system" structure:"payment_system"`
	// @inject_tag: bson:"group_alias" structure:"group_alias"
	GroupAlias           string   `protobuf:"bytes,5,opt,name=group_alias,json=groupAlias,proto3" json:"group_alias,omitempty" bson:"group_alias" structure:"group_alias"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *PaymentMethodOrder) Reset()         { *m = PaymentMethodOrder{} }
func (m *PaymentMethodOrder) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodOrder) ProtoMessage()    {}
func (*PaymentMethodOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{8}
}
func (m *PaymentMethodOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodOrder.Unmarshal(m, b)
}
func (m *PaymentMethodOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodOrder.Marshal(b, m, deterministic)
}
func (dst *PaymentMethodOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodOrder.Merge(dst, src)
}
func (m *PaymentMethodOrder) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodOrder.Size(m)
}
func (m *PaymentMethodOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodOrder proto.InternalMessageInfo

func (m *PaymentMethodOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethodOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentMethodOrder) GetParams() *PaymentMethodParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PaymentMethodOrder) GetPaymentSystem() *PaymentSystem {
	if m != nil {
		return m.PaymentSystem
	}
	return nil
}

func (m *PaymentMethodOrder) GetGroupAlias() string {
	if m != nil {
		return m.GroupAlias
	}
	return ""
}

type PaymentMethodParams struct {
	// @inject_tag: bson:"handler" structure:"handler"
	Handler string `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty" bson:"handler" structure:"handler"`
	// @inject_tag: bson:"terminal" structure:"terminal"
	Terminal string `protobuf:"bytes,2,opt,name=terminal,proto3" json:"terminal,omitempty" bson:"terminal" structure:"terminal"`
	// @inject_tag: bson:"external_id" structure:"external_id"
	ExternalId string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty" bson:"external_id" structure:"external_id"`
	// @inject_tag: bson:"other" structure:"other"
	Other                map[string]string `protobuf:"bytes,4,rep,name=other,proto3" json:"other,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"other" structure:"other"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-" structure:"-"`
}

func (m *PaymentMethodParams) Reset()         { *m = PaymentMethodParams{} }
func (m *PaymentMethodParams) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodParams) ProtoMessage()    {}
func (*PaymentMethodParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{9}
}
func (m *PaymentMethodParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodParams.Unmarshal(m, b)
}
func (m *PaymentMethodParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodParams.Marshal(b, m, deterministic)
}
func (dst *PaymentMethodParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodParams.Merge(dst, src)
}
func (m *PaymentMethodParams) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodParams.Size(m)
}
func (m *PaymentMethodParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodParams.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodParams proto.InternalMessageInfo

func (m *PaymentMethodParams) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *PaymentMethodParams) GetTerminal() string {
	if m != nil {
		return m.Terminal
	}
	return ""
}

func (m *PaymentMethodParams) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *PaymentMethodParams) GetOther() map[string]string {
	if m != nil {
		return m.Other
	}
	return nil
}

type PaymentSystem struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	// @inject_tag: bson:"accounting_currency" structure:"accounting_currency"
	AccountingCurrency *Currency `protobuf:"bytes,4,opt,name=accounting_currency,json=accountingCurrency,proto3" json:"accounting_currency,omitempty" bson:"accounting_currency" structure:"accounting_currency"`
	// @inject_tag: bson:"is_active" structure:"is_active"
	IsActive             bool     `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active" structure:"is_active"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *PaymentSystem) Reset()         { *m = PaymentSystem{} }
func (m *PaymentSystem) String() string { return proto.CompactTextString(m) }
func (*PaymentSystem) ProtoMessage()    {}
func (*PaymentSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{10}
}
func (m *PaymentSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentSystem.Unmarshal(m, b)
}
func (m *PaymentSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentSystem.Marshal(b, m, deterministic)
}
func (dst *PaymentSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentSystem.Merge(dst, src)
}
func (m *PaymentSystem) XXX_Size() int {
	return xxx_messageInfo_PaymentSystem.Size(m)
}
func (m *PaymentSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentSystem.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentSystem proto.InternalMessageInfo

func (m *PaymentSystem) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PaymentSystem) GetAccountingCurrency() *Currency {
	if m != nil {
		return m.AccountingCurrency
	}
	return nil
}

func (m *PaymentSystem) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type FixedPackage struct {
	// @inject_tag: bson:"id" structure:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id" structure:"id"`
	// @inject_tag: bson:"name" structure:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name" structure:"name"`
	// @inject_tag: bson:"currency_int" structure:"currency_int"
	CurrencyInt int32 `protobuf:"varint,3,opt,name=currency_int,json=currencyInt,proto3" json:"currency_int,omitempty" bson:"currency_int" structure:"currency_int"`
	// @inject_tag: bson:"price" structure:"price"
	Price float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty" bson:"price" structure:"price"`
	// @inject_tag: bson:"is_active" structure:"is_active"
	IsActive             bool     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active" structure:"is_active"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FixedPackage) Reset()         { *m = FixedPackage{} }
func (m *FixedPackage) String() string { return proto.CompactTextString(m) }
func (*FixedPackage) ProtoMessage()    {}
func (*FixedPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{11}
}
func (m *FixedPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedPackage.Unmarshal(m, b)
}
func (m *FixedPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedPackage.Marshal(b, m, deterministic)
}
func (dst *FixedPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedPackage.Merge(dst, src)
}
func (m *FixedPackage) XXX_Size() int {
	return xxx_messageInfo_FixedPackage.Size(m)
}
func (m *FixedPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedPackage.DiscardUnknown(m)
}

var xxx_messageInfo_FixedPackage proto.InternalMessageInfo

func (m *FixedPackage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FixedPackage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FixedPackage) GetCurrencyInt() int32 {
	if m != nil {
		return m.CurrencyInt
	}
	return 0
}

func (m *FixedPackage) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *FixedPackage) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type FixedPackages struct {
	FixedPackage         []*FixedPackage `protobuf:"bytes,1,rep,name=fixed_package,json=fixedPackage,proto3" json:"fixed_package,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte          `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32           `json:"-" bson:"-" structure:"-"`
}

func (m *FixedPackages) Reset()         { *m = FixedPackages{} }
func (m *FixedPackages) String() string { return proto.CompactTextString(m) }
func (*FixedPackages) ProtoMessage()    {}
func (*FixedPackages) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{12}
}
func (m *FixedPackages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedPackages.Unmarshal(m, b)
}
func (m *FixedPackages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedPackages.Marshal(b, m, deterministic)
}
func (dst *FixedPackages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedPackages.Merge(dst, src)
}
func (m *FixedPackages) XXX_Size() int {
	return xxx_messageInfo_FixedPackages.Size(m)
}
func (m *FixedPackages) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedPackages.DiscardUnknown(m)
}

var xxx_messageInfo_FixedPackages proto.InternalMessageInfo

func (m *FixedPackages) GetFixedPackage() []*FixedPackage {
	if m != nil {
		return m.FixedPackage
	}
	return nil
}

type OrderFee struct {
	// @inject_tag: bson:"amount_payment_method_currency" structure:"amount_payment_method_currency"
	AmountPaymentMethodCurrency float64 `protobuf:"fixed64,1,opt,name=AmountPaymentMethodCurrency,proto3" json:"AmountPaymentMethodCurrency,omitempty" bson:"amount_payment_method_currency" structure:"amount_payment_method_currency"`
	// @inject_tag: bson:"amount_merchant_currency" structure:"amount_merchant_currency"
	AmountMerchantCurrency float64  `protobuf:"fixed64,2,opt,name=AmountMerchantCurrency,proto3" json:"AmountMerchantCurrency,omitempty" bson:"amount_merchant_currency" structure:"amount_merchant_currency"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized       []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache          int32    `json:"-" bson:"-" structure:"-"`
}

func (m *OrderFee) Reset()         { *m = OrderFee{} }
func (m *OrderFee) String() string { return proto.CompactTextString(m) }
func (*OrderFee) ProtoMessage()    {}
func (*OrderFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{13}
}
func (m *OrderFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFee.Unmarshal(m, b)
}
func (m *OrderFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFee.Marshal(b, m, deterministic)
}
func (dst *OrderFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFee.Merge(dst, src)
}
func (m *OrderFee) XXX_Size() int {
	return xxx_messageInfo_OrderFee.Size(m)
}
func (m *OrderFee) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFee.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFee proto.InternalMessageInfo

func (m *OrderFee) GetAmountPaymentMethodCurrency() float64 {
	if m != nil {
		return m.AmountPaymentMethodCurrency
	}
	return 0
}

func (m *OrderFee) GetAmountMerchantCurrency() float64 {
	if m != nil {
		return m.AmountMerchantCurrency
	}
	return 0
}

type OrderFeePsp struct {
	// @inject_tag: bson:"amount_payment_method_currency" structure:"amount_payment_method_currency"
	AmountPaymentMethodCurrency float64 `protobuf:"fixed64,1,opt,name=AmountPaymentMethodCurrency,proto3" json:"AmountPaymentMethodCurrency,omitempty" bson:"amount_payment_method_currency" structure:"amount_payment_method_currency"`
	// @inject_tag: bson:"amount_merchant_currency" structure:"amount_merchant_currency"
	AmountMerchantCurrency float64 `protobuf:"fixed64,2,opt,name=AmountMerchantCurrency,proto3" json:"AmountMerchantCurrency,omitempty" bson:"amount_merchant_currency" structure:"amount_merchant_currency"`
	// @inject_tag: bson:"amount_psp_currency" structure:"amount_psp_currency"
	AmountPspCurrency    float64  `protobuf:"fixed64,3,opt,name=AmountPspCurrency,proto3" json:"AmountPspCurrency,omitempty" bson:"amount_psp_currency" structure:"amount_psp_currency"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *OrderFeePsp) Reset()         { *m = OrderFeePsp{} }
func (m *OrderFeePsp) String() string { return proto.CompactTextString(m) }
func (*OrderFeePsp) ProtoMessage()    {}
func (*OrderFeePsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{14}
}
func (m *OrderFeePsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFeePsp.Unmarshal(m, b)
}
func (m *OrderFeePsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFeePsp.Marshal(b, m, deterministic)
}
func (dst *OrderFeePsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFeePsp.Merge(dst, src)
}
func (m *OrderFeePsp) XXX_Size() int {
	return xxx_messageInfo_OrderFeePsp.Size(m)
}
func (m *OrderFeePsp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFeePsp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFeePsp proto.InternalMessageInfo

func (m *OrderFeePsp) GetAmountPaymentMethodCurrency() float64 {
	if m != nil {
		return m.AmountPaymentMethodCurrency
	}
	return 0
}

func (m *OrderFeePsp) GetAmountMerchantCurrency() float64 {
	if m != nil {
		return m.AmountMerchantCurrency
	}
	return 0
}

func (m *OrderFeePsp) GetAmountPspCurrency() float64 {
	if m != nil {
		return m.AmountPspCurrency
	}
	return 0
}

// Contain information about payment system commission in other currencies
type OrderFeePaymentSystem struct {
	// @inject_tag: bson:"amount_payment_method_currency" structure:"amount_payment_method_currency"
	AmountPaymentMethodCurrency float64 `protobuf:"fixed64,1,opt,name=AmountPaymentMethodCurrency,proto3" json:"AmountPaymentMethodCurrency,omitempty" bson:"amount_payment_method_currency" structure:"amount_payment_method_currency"`
	// @inject_tag: bson:"amount_merchant_currency" structure:"amount_merchant_currency"
	AmountMerchantCurrency float64 `protobuf:"fixed64,2,opt,name=AmountMerchantCurrency,proto3" json:"AmountMerchantCurrency,omitempty" bson:"amount_merchant_currency" structure:"amount_merchant_currency"`
	// @inject_tag: bson:"amount_payment_system_currency" structure:"amount_payment_system_currency"
	AmountPaymentSystemCurrency float64  `protobuf:"fixed64,3,opt,name=AmountPaymentSystemCurrency,proto3" json:"AmountPaymentSystemCurrency,omitempty" bson:"amount_payment_system_currency" structure:"amount_payment_system_currency"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized            []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache               int32    `json:"-" bson:"-" structure:"-"`
}

func (m *OrderFeePaymentSystem) Reset()         { *m = OrderFeePaymentSystem{} }
func (m *OrderFeePaymentSystem) String() string { return proto.CompactTextString(m) }
func (*OrderFeePaymentSystem) ProtoMessage()    {}
func (*OrderFeePaymentSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{15}
}
func (m *OrderFeePaymentSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFeePaymentSystem.Unmarshal(m, b)
}
func (m *OrderFeePaymentSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFeePaymentSystem.Marshal(b, m, deterministic)
}
func (dst *OrderFeePaymentSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFeePaymentSystem.Merge(dst, src)
}
func (m *OrderFeePaymentSystem) XXX_Size() int {
	return xxx_messageInfo_OrderFeePaymentSystem.Size(m)
}
func (m *OrderFeePaymentSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFeePaymentSystem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFeePaymentSystem proto.InternalMessageInfo

func (m *OrderFeePaymentSystem) GetAmountPaymentMethodCurrency() float64 {
	if m != nil {
		return m.AmountPaymentMethodCurrency
	}
	return 0
}

func (m *OrderFeePaymentSystem) GetAmountMerchantCurrency() float64 {
	if m != nil {
		return m.AmountMerchantCurrency
	}
	return 0
}

func (m *OrderFeePaymentSystem) GetAmountPaymentSystemCurrency() float64 {
	if m != nil {
		return m.AmountPaymentSystemCurrency
	}
	return 0
}

type ProjectPaymentMethod struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AddedAt              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-"`
}

func (m *ProjectPaymentMethod) Reset()         { *m = ProjectPaymentMethod{} }
func (m *ProjectPaymentMethod) String() string { return proto.CompactTextString(m) }
func (*ProjectPaymentMethod) ProtoMessage()    {}
func (*ProjectPaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{16}
}
func (m *ProjectPaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectPaymentMethod.Unmarshal(m, b)
}
func (m *ProjectPaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectPaymentMethod.Marshal(b, m, deterministic)
}
func (dst *ProjectPaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectPaymentMethod.Merge(dst, src)
}
func (m *ProjectPaymentMethod) XXX_Size() int {
	return xxx_messageInfo_ProjectPaymentMethod.Size(m)
}
func (m *ProjectPaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectPaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectPaymentMethod proto.InternalMessageInfo

func (m *ProjectPaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectPaymentMethod) GetAddedAt() *timestamp.Timestamp {
	if m != nil {
		return m.AddedAt
	}
	return nil
}

type ProjectPaymentMethods struct {
	PaymentMethods       []*ProjectPaymentMethod `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte                  `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32                   `json:"-" bson:"-" structure:"-"`
}

func (m *ProjectPaymentMethods) Reset()         { *m = ProjectPaymentMethods{} }
func (m *ProjectPaymentMethods) String() string { return proto.CompactTextString(m) }
func (*ProjectPaymentMethods) ProtoMessage()    {}
func (*ProjectPaymentMethods) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{17}
}
func (m *ProjectPaymentMethods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectPaymentMethods.Unmarshal(m, b)
}
func (m *ProjectPaymentMethods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectPaymentMethods.Marshal(b, m, deterministic)
}
func (dst *ProjectPaymentMethods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectPaymentMethods.Merge(dst, src)
}
func (m *ProjectPaymentMethods) XXX_Size() int {
	return xxx_messageInfo_ProjectPaymentMethods.Size(m)
}
func (m *ProjectPaymentMethods) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectPaymentMethods.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectPaymentMethods proto.InternalMessageInfo

func (m *ProjectPaymentMethods) GetPaymentMethods() []*ProjectPaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

type CurrencyRate struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	// @inject_tag: bson:"currency_from" structure:"currency_from"
	CurrencyFrom int32 `protobuf:"varint,2,opt,name=currency_from,json=currencyFrom,proto3" json:"currency_from,omitempty" bson:"currency_from" structure:"currency_from"`
	// @inject_tag: bson:"currency_to" structure:"currency_to"
	CurrencyTo int32 `protobuf:"varint,3,opt,name=currency_to,json=currencyTo,proto3" json:"currency_to,omitempty" bson:"currency_to" structure:"currency_to"`
	// @inject_tag: bson:"rate" structure:"rate"
	Rate float64 `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty" bson:"rate" structure:"rate"`
	// @inject_tag: bson:"is_active" structure:"rate"
	IsActive             bool     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active" structure:"rate"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *CurrencyRate) Reset()         { *m = CurrencyRate{} }
func (m *CurrencyRate) String() string { return proto.CompactTextString(m) }
func (*CurrencyRate) ProtoMessage()    {}
func (*CurrencyRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{18}
}
func (m *CurrencyRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyRate.Unmarshal(m, b)
}
func (m *CurrencyRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyRate.Marshal(b, m, deterministic)
}
func (dst *CurrencyRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyRate.Merge(dst, src)
}
func (m *CurrencyRate) XXX_Size() int {
	return xxx_messageInfo_CurrencyRate.Size(m)
}
func (m *CurrencyRate) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyRate.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyRate proto.InternalMessageInfo

func (m *CurrencyRate) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CurrencyRate) GetCurrencyFrom() int32 {
	if m != nil {
		return m.CurrencyFrom
	}
	return 0
}

func (m *CurrencyRate) GetCurrencyTo() int32 {
	if m != nil {
		return m.CurrencyTo
	}
	return 0
}

func (m *CurrencyRate) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *CurrencyRate) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type PaymentMethod struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	// @inject_tag: bson:"group_alias" structure:"group_alias"
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty" bson:"group_alias" structure:"group_alias"`
	// @inject_tag: bson:"currencies" structure:"currencies"
	Currencies []int32 `protobuf:"varint,3,rep,packed,name=currencies,proto3" json:"currencies,omitempty" bson:"currencies" structure:"currencies"`
	// @inject_tag: bson:"min_payment_amount" structure:"min_payment_amount"
	MinPaymentAmount float64 `protobuf:"fixed64,4,opt,name=min_payment_amount,json=minPaymentAmount,proto3" json:"min_payment_amount,omitempty" bson:"min_payment_amount" structure:"min_payment_amount"`
	// @inject_tag: bson:"max_payment_amount" structure:"max_payment_amount"
	MaxPaymentAmount float64 `protobuf:"fixed64,5,opt,name=max_payment_amount,json=maxPaymentAmount,proto3" json:"max_payment_amount,omitempty" bson:"max_payment_amount" structure:"max_payment_amount"`
	// @inject_tag: bson:"params" structure:"params"
	Params *PaymentMethodParams `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty" bson:"params" structure:"params"`
	// @inject_tag: bson:"icon" structure:"icon"
	Icon string `protobuf:"bytes,7,opt,name=Icon,proto3" json:"Icon,omitempty" bson:"icon" structure:"icon"`
	// @inject_tag: bson:"payment_system" structure:"payment_system"
	PaymentSystem *PaymentSystem `protobuf:"bytes,8,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty" bson:"payment_system" structure:"payment_system"`
	// @inject_tag: bson:"type" structure:"type"
	Type string `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty" bson:"type" structure:"type"`
	// @inject_tag: bson:"account_regexp" structure:"account_regexp"
	AccountRegexp string `protobuf:"bytes,10,opt,name=account_regexp,json=accountRegexp,proto3" json:"account_regexp,omitempty" bson:"account_regexp" structure:"account_regexp"`
	// @inject_tag: bson:"is_active" structure:"is_active"
	IsActive             bool     `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active" structure:"is_active"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_4931f8e93191feff, []int{19}
}
func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (dst *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(dst, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PaymentMethod) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *PaymentMethod) GetCurrencies() []int32 {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *PaymentMethod) GetMinPaymentAmount() float64 {
	if m != nil {
		return m.MinPaymentAmount
	}
	return 0
}

func (m *PaymentMethod) GetMaxPaymentAmount() float64 {
	if m != nil {
		return m.MaxPaymentAmount
	}
	return 0
}

func (m *PaymentMethod) GetParams() *PaymentMethodParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PaymentMethod) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *PaymentMethod) GetPaymentSystem() *PaymentSystem {
	if m != nil {
		return m.PaymentSystem
	}
	return nil
}

func (m *PaymentMethod) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PaymentMethod) GetAccountRegexp() string {
	if m != nil {
		return m.AccountRegexp
	}
	return ""
}

func (m *PaymentMethod) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func init() {
	proto.RegisterType((*Name)(nil), "billing.Name")
	proto.RegisterType((*OrderCreateRequest)(nil), "billing.OrderCreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "billing.OrderCreateRequest.OtherEntry")
	proto.RegisterMapType((map[string]string)(nil), "billing.OrderCreateRequest.RawParamsEntry")
	proto.RegisterType((*Project)(nil), "billing.Project")
	proto.RegisterMapType((map[string]*FixedPackages)(nil), "billing.Project.FixedPackageEntry")
	proto.RegisterMapType((map[string]*ProjectPaymentMethods)(nil), "billing.Project.PaymentMethodsEntry")
	proto.RegisterType((*ProjectOrder)(nil), "billing.ProjectOrder")
	proto.RegisterType((*Merchant)(nil), "billing.Merchant")
	proto.RegisterType((*Order)(nil), "billing.Order")
	proto.RegisterMapType((map[string]string)(nil), "billing.Order.PaymentMethodTxnParamsEntry")
	proto.RegisterMapType((map[string]string)(nil), "billing.Order.PaymentRequisitesEntry")
	proto.RegisterMapType((map[string]string)(nil), "billing.Order.ProjectParamsEntry")
	proto.RegisterType((*Currency)(nil), "billing.Currency")
	proto.RegisterType((*PayerData)(nil), "billing.PayerData")
	proto.RegisterType((*PaymentMethodOrder)(nil), "billing.PaymentMethodOrder")
	proto.RegisterType((*PaymentMethodParams)(nil), "billing.PaymentMethodParams")
	proto.RegisterMapType((map[string]string)(nil), "billing.PaymentMethodParams.OtherEntry")
	proto.RegisterType((*PaymentSystem)(nil), "billing.PaymentSystem")
	proto.RegisterType((*FixedPackage)(nil), "billing.FixedPackage")
	proto.RegisterType((*FixedPackages)(nil), "billing.FixedPackages")
	proto.RegisterType((*OrderFee)(nil), "billing.OrderFee")
	proto.RegisterType((*OrderFeePsp)(nil), "billing.OrderFeePsp")
	proto.RegisterType((*OrderFeePaymentSystem)(nil), "billing.OrderFeePaymentSystem")
	proto.RegisterType((*ProjectPaymentMethod)(nil), "billing.ProjectPaymentMethod")
	proto.RegisterType((*ProjectPaymentMethods)(nil), "billing.ProjectPaymentMethods")
	proto.RegisterType((*CurrencyRate)(nil), "billing.CurrencyRate")
	proto.RegisterType((*PaymentMethod)(nil), "billing.PaymentMethod")
}

func init() { proto.RegisterFile("billing/billing.proto", fileDescriptor_billing_4931f8e93191feff) }

var fileDescriptor_billing_4931f8e93191feff = []byte{
	// 2598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x59, 0x4b, 0x73, 0x1b, 0xc7,
	0xf1, 0x2f, 0x90, 0x04, 0x08, 0x34, 0x1e, 0x24, 0x87, 0xaf, 0x25, 0x28, 0x4a, 0x14, 0x64, 0x3d,
	0xca, 0x7f, 0x99, 0xf4, 0x9f, 0xb2, 0x53, 0x8e, 0xe2, 0x87, 0x20, 0x4a, 0x8c, 0x11, 0xc7, 0x12,
	0x6b, 0x4d, 0x3b, 0xaf, 0x72, 0xb6, 0x86, 0xbb, 0x43, 0x72, 0xac, 0xc5, 0xee, 0x66, 0x67, 0x40,
	0x11, 0x39, 0xa5, 0x52, 0x39, 0xe4, 0x9c, 0xaa, 0xe4, 0x2b, 0xe4, 0x9a, 0x4b, 0xbe, 0x46, 0x2e,
	0xf9, 0x0c, 0x39, 0xe6, 0x0b, 0xe4, 0x94, 0x9a, 0xd7, 0x62, 0x5f, 0x80, 0xc4, 0x5c, 0x7c, 0x02,
	0xa6, 0xa7, 0xbb, 0xa7, 0x67, 0xba, 0xfb, 0xd7, 0x3d, 0xb3, 0xb0, 0x7e, 0x4a, 0x7d, 0x9f, 0x06,
	0xe7, 0xfb, 0xfa, 0x77, 0x2f, 0x8a, 0x43, 0x1e, 0xa2, 0x45, 0x3d, 0xec, 0xde, 0x3a, 0x0f, 0xc3,
	0x73, 0x9f, 0xec, 0x4b, 0xf2, 0xe9, 0xe8, 0x6c, 0x9f, 0xd3, 0x21, 0x61, 0x1c, 0x0f, 0x23, 0xc5,
	0xd9, 0xbb, 0x07, 0x0b, 0x2f, 0xf0, 0x90, 0xa0, 0x0e, 0xcc, 0x91, 0xc0, 0xaa, 0xec, 0x56, 0x1e,
	0x34, 0xec, 0x39, 0x12, 0x88, 0x71, 0x3c, 0xb2, 0xe6, 0xd4, 0x38, 0x1e, 0xf5, 0xfe, 0x5a, 0x03,
	0xf4, 0x32, 0xf6, 0x48, 0x7c, 0x18, 0x13, 0xcc, 0x89, 0x4d, 0x7e, 0x33, 0x22, 0x8c, 0xa3, 0x1d,
	0x80, 0x28, 0x0e, 0xbf, 0x23, 0x2e, 0x77, 0xa8, 0xa7, 0xc5, 0x1b, 0x9a, 0x32, 0xf0, 0xd0, 0x0d,
	0x68, 0x30, 0x7a, 0x1e, 0x60, 0x3e, 0x8a, 0x89, 0x56, 0x36, 0x21, 0xa0, 0x0d, 0xa8, 0xe1, 0x61,
	0x38, 0x0a, 0xb8, 0x35, 0xbf, 0x5b, 0x79, 0x50, 0xb1, 0xf5, 0x08, 0x75, 0xa1, 0xee, 0x8e, 0xe2,
	0x98, 0x04, 0xee, 0xd8, 0x5a, 0x90, 0x42, 0xc9, 0x18, 0x59, 0xb0, 0x88, 0x5d, 0x57, 0x0a, 0x55,
	0xe5, 0x94, 0x19, 0xa2, 0x2d, 0xa8, 0x87, 0xc2, 0x40, 0x61, 0x48, 0x4d, 0x4d, 0xc9, 0xf1, 0xc0,
	0x43, 0xbb, 0xd0, 0xf4, 0x08, 0x73, 0x63, 0x1a, 0x71, 0x1a, 0x06, 0xd6, 0xa2, 0x9c, 0x4d, 0x93,
	0xd0, 0x5d, 0xe8, 0x44, 0x78, 0x3c, 0x24, 0x01, 0x77, 0x86, 0x84, 0x5f, 0x84, 0x9e, 0x55, 0x97,
	0x4c, 0x6d, 0x4d, 0xfd, 0x52, 0x12, 0xc5, 0x76, 0x47, 0xb1, 0xef, 0x5c, 0x92, 0x98, 0x9e, 0x8d,
	0xad, 0x86, 0xda, 0xd0, 0x28, 0xf6, 0xbf, 0x91, 0x04, 0x33, 0x1d, 0x84, 0x5c, 0x4c, 0x43, 0x32,
	0xfd, 0x42, 0x12, 0xd0, 0x2d, 0x68, 0x8a, 0x69, 0x36, 0x72, 0x5d, 0xc2, 0x98, 0xd5, 0x94, 0xf3,
	0x42, 0xe2, 0x2b, 0x45, 0x11, 0x5b, 0x10, 0x0c, 0x67, 0x98, 0xfa, 0x56, 0x4b, 0x6d, 0x61, 0x14,
	0xfb, 0x47, 0x98, 0xfa, 0x42, 0x36, 0xc2, 0x63, 0x12, 0x3b, 0x64, 0x28, 0x66, 0xdb, 0x4a, 0x56,
	0x92, 0x9e, 0x0f, 0x33, 0x0c, 0xd1, 0x45, 0x18, 0x10, 0xab, 0x93, 0x62, 0x38, 0x16, 0x14, 0x71,
	0xda, 0x31, 0x39, 0x17, 0xfb, 0x5f, 0x92, 0x73, 0x7a, 0x24, 0x16, 0x55, 0x82, 0x34, 0xb2, 0x96,
	0xd5, 0xa2, 0x72, 0x3c, 0x88, 0xd0, 0xc7, 0x50, 0x0d, 0xf9, 0x05, 0x89, 0xad, 0x95, 0xdd, 0xf9,
	0x07, 0xcd, 0x83, 0x7b, 0x7b, 0x26, 0xca, 0x8a, 0x91, 0xb0, 0xf7, 0x52, 0x30, 0x3e, 0x0f, 0x78,
	0x3c, 0xb6, 0x95, 0x10, 0x1a, 0x00, 0xc4, 0xf8, 0xb5, 0x13, 0xe1, 0x18, 0x0f, 0x99, 0x85, 0xa4,
	0x8a, 0x77, 0x67, 0xa9, 0xb0, 0xf1, 0xeb, 0x63, 0xc9, 0xac, 0xd4, 0x34, 0x62, 0x33, 0x16, 0x36,
	0x0a, 0x55, 0xa7, 0xa1, 0x37, 0xb6, 0x56, 0x95, 0x8d, 0x31, 0x7e, 0xfd, 0x34, 0xf4, 0xc6, 0x68,
	0x13, 0x16, 0x29, 0x73, 0xbe, 0x63, 0x61, 0x60, 0xad, 0xed, 0x56, 0x1e, 0xd4, 0xed, 0x1a, 0x65,
	0x3f, 0x61, 0x61, 0xd0, 0xfd, 0x08, 0x60, 0x62, 0x13, 0x5a, 0x86, 0xf9, 0x57, 0x64, 0xac, 0x23,
	0x54, 0xfc, 0x45, 0x6b, 0x50, 0xbd, 0xc4, 0xfe, 0xc8, 0xc4, 0xa5, 0x1a, 0x3c, 0x9e, 0xfb, 0xa8,
	0xd2, 0xfd, 0x18, 0x3a, 0x59, 0x53, 0xae, 0x23, 0xdd, 0xfb, 0x77, 0x03, 0x16, 0x8f, 0x55, 0x06,
	0x88, 0x2c, 0x4a, 0xd2, 0x62, 0x8e, 0x7a, 0xe8, 0x53, 0x58, 0x71, 0xb1, 0xef, 0x9f, 0x62, 0xf7,
	0x95, 0x93, 0x84, 0xb8, 0xd0, 0xd0, 0x3c, 0x58, 0x49, 0x4e, 0xe6, 0x50, 0x4f, 0xd8, 0xcb, 0x86,
	0xd7, 0x50, 0xd0, 0xff, 0xa5, 0xe4, 0x65, 0xfe, 0xba, 0xa1, 0x2f, 0x93, 0xa7, 0x31, 0x61, 0x3e,
	0xd6, 0x74, 0xf4, 0x09, 0x6c, 0xbb, 0xf2, 0x7c, 0x1d, 0x1a, 0x5c, 0x86, 0xd4, 0x25, 0x0e, 0xf6,
	0xfd, 0xf0, 0x35, 0xf1, 0x9c, 0x51, 0xec, 0x33, 0x6b, 0x61, 0x77, 0xfe, 0x41, 0xc3, 0xb6, 0x14,
	0xcb, 0x40, 0x71, 0xf4, 0x15, 0xc3, 0xd7, 0xb1, 0xcf, 0xd0, 0x7b, 0x50, 0x1f, 0x92, 0xd8, 0xbd,
	0xc0, 0x3a, 0xd5, 0xd2, 0x26, 0x7e, 0xa9, 0x27, 0xec, 0x84, 0x05, 0x7d, 0x0a, 0x37, 0x28, 0x53,
	0x2b, 0x38, 0xde, 0x38, 0xc0, 0x43, 0xea, 0xea, 0x44, 0x50, 0xcb, 0xd5, 0xa4, 0x73, 0x2c, 0xca,
	0xe4, 0x1a, 0xcf, 0x14, 0x87, 0x4a, 0x0c, 0xb9, 0xdc, 0x53, 0xb8, 0x59, 0x90, 0x8f, 0x89, 0x47,
	0x63, 0x81, 0x2d, 0x52, 0xc3, 0xa2, 0xd4, 0xd0, 0xcd, 0x6a, 0xb0, 0x35, 0x8b, 0xd4, 0xf1, 0x18,
	0x96, 0x7c, 0x3a, 0xa4, 0x9c, 0x4d, 0x0e, 0xb7, 0x3e, 0xed, 0x70, 0x3b, 0x8a, 0x33, 0x39, 0xda,
	0x87, 0x80, 0x86, 0xf8, 0xca, 0x31, 0x28, 0xa0, 0x81, 0xa9, 0x21, 0x81, 0x69, 0x79, 0x88, 0xaf,
	0x8e, 0xd5, 0x44, 0x5f, 0x41, 0x94, 0xe0, 0xa6, 0x41, 0x9e, 0x1b, 0x34, 0x37, 0x0d, 0xb2, 0xdc,
	0x08, 0x16, 0x02, 0x3c, 0x24, 0x3a, 0xe3, 0xe5, 0x7f, 0x74, 0x07, 0xda, 0xfa, 0x78, 0x64, 0x46,
	0x33, 0xab, 0x25, 0xfd, 0xd1, 0x52, 0x44, 0x99, 0xd3, 0x4c, 0x2c, 0x13, 0x06, 0xfe, 0xd8, 0x39,
	0xa3, 0x57, 0xc4, 0xd3, 0xab, 0x30, 0x99, 0xfc, 0x75, 0x7b, 0x59, 0xcc, 0x1c, 0x89, 0x09, 0xb5,
	0x0a, 0x13, 0xf0, 0xc3, 0x88, 0x1b, 0x13, 0xee, 0x88, 0x60, 0xed, 0x68, 0xb8, 0x95, 0x94, 0x2f,
	0xc8, 0x18, 0xbd, 0x0b, 0x2b, 0x8c, 0x04, 0x9e, 0x93, 0x5e, 0x56, 0x62, 0x41, 0xdd, 0x5e, 0x12,
	0x13, 0x2f, 0x26, 0x2b, 0x0b, 0x5e, 0x81, 0x44, 0xee, 0x05, 0x71, 0x5f, 0x39, 0x06, 0x70, 0x15,
	0x3a, 0x2c, 0x8d, 0x62, 0xff, 0x50, 0xd0, 0xfb, 0x1a, 0x78, 0xf7, 0x60, 0x55, 0xf0, 0x46, 0x71,
	0x28, 0x40, 0xcc, 0x9c, 0x89, 0xb5, 0x22, 0xb9, 0x85, 0x9a, 0x63, 0x35, 0xa3, 0xcf, 0xc4, 0xe8,
	0x4e, 0x9c, 0x2b, 0xe1, 0x0e, 0x25, 0xba, 0x8d, 0x47, 0x25, 0xec, 0xbd, 0x0f, 0x6b, 0x19, 0x5e,
	0x83, 0x9d, 0x0a, 0x04, 0x50, 0x8a, 0xdd, 0x60, 0xe8, 0x8f, 0xa1, 0xad, 0x4e, 0x2b, 0xc2, 0xee,
	0x2b, 0x7c, 0x4e, 0xac, 0x4d, 0x09, 0x3c, 0xbd, 0x24, 0x02, 0x74, 0x6e, 0xee, 0xc9, 0xa3, 0x3b,
	0x56, 0x4c, 0x0a, 0x70, 0x5a, 0x67, 0x29, 0x12, 0xfa, 0x12, 0x96, 0xb2, 0x25, 0x81, 0x59, 0x96,
	0x54, 0xf5, 0x4e, 0x41, 0xd5, 0x71, 0xba, 0x48, 0x68, 0xf4, 0xea, 0x64, 0x2a, 0x07, 0x43, 0xdb,
	0xd0, 0x10, 0xf1, 0xed, 0x72, 0x7a, 0x49, 0x34, 0x52, 0xd5, 0x29, 0xeb, 0xcb, 0x71, 0xf7, 0x67,
	0xb0, 0x52, 0x30, 0xa7, 0x04, 0x74, 0x1e, 0xa6, 0x41, 0xa7, 0x79, 0xb0, 0x91, 0x18, 0x92, 0x16,
	0x66, 0x69, 0x28, 0xc3, 0xb0, 0x5a, 0x62, 0x5c, 0x89, 0xea, 0x0f, 0xb2, 0xaa, 0x6f, 0xe6, 0xf7,
	0x98, 0xd5, 0x92, 0xc6, 0xbb, 0xbf, 0xcc, 0x43, 0x4b, 0x33, 0x49, 0x4c, 0x4f, 0x81, 0x5e, 0x4b,
	0x82, 0x9e, 0x89, 0xfe, 0xb9, 0x54, 0xf4, 0xe7, 0x4a, 0xe1, 0xfc, 0xcc, 0x52, 0xb8, 0x90, 0x2d,
	0x85, 0x85, 0xcc, 0xa9, 0x96, 0x64, 0x4e, 0x36, 0x17, 0x6a, 0x6f, 0x95, 0x0b, 0x8b, 0xd7, 0xc8,
	0x85, 0xfa, 0xb5, 0x72, 0xa1, 0x31, 0x2d, 0x17, 0x4a, 0x01, 0x1d, 0xa6, 0x00, 0x7a, 0x1a, 0x91,
	0x5b, 0x6f, 0x44, 0xe4, 0xde, 0xdf, 0xe6, 0xa0, 0x6e, 0xc8, 0x05, 0xa7, 0xdc, 0x82, 0x26, 0xb9,
	0xe2, 0x24, 0x0e, 0xb0, 0x2f, 0x1a, 0x26, 0xe5, 0x1b, 0x30, 0xa4, 0x81, 0x27, 0x16, 0x4b, 0x40,
	0x74, 0x7e, 0x1a, 0x88, 0x4e, 0xfa, 0xb2, 0x77, 0xa0, 0x43, 0x99, 0x73, 0x89, 0xb9, 0x43, 0x02,
	0x7c, 0xea, 0x13, 0x4f, 0x7a, 0xad, 0x6e, 0xb7, 0x28, 0xfb, 0x06, 0xf3, 0xe7, 0x8a, 0x86, 0x9e,
	0xc0, 0x0e, 0x65, 0x8e, 0x1b, 0x0e, 0x87, 0x94, 0x31, 0x1a, 0x06, 0x0e, 0x0f, 0x9d, 0x11, 0x13,
	0x5d, 0x8d, 0x16, 0xaa, 0x4a, 0xa1, 0x2d, 0xca, 0x0e, 0x13, 0x9e, 0x93, 0xf0, 0x6b, 0x26, 0xaa,
	0xb8, 0xd2, 0xb0, 0x01, 0x35, 0xc6, 0x31, 0x1f, 0xa9, 0x82, 0x52, 0xb5, 0xf5, 0x08, 0x3d, 0x83,
	0xe5, 0x33, 0x1a, 0x33, 0x3e, 0x81, 0x64, 0x2e, 0xfd, 0xd9, 0x3c, 0xe8, 0xee, 0xa9, 0x1e, 0x78,
	0xcf, 0xf4, 0xc0, 0x7b, 0x27, 0xa6, 0x07, 0xb6, 0x3b, 0x52, 0xc6, 0x80, 0x35, 0xef, 0xfd, 0x67,
	0x0d, 0xaa, 0xf9, 0x20, 0x56, 0x95, 0x7b, 0x1f, 0x16, 0x75, 0x5b, 0xab, 0x33, 0x64, 0x3d, 0x9f,
	0x21, 0x52, 0xce, 0x36, 0x5c, 0xe8, 0x01, 0x2c, 0x9b, 0xce, 0x38, 0x69, 0x4b, 0x55, 0x98, 0x77,
	0xa2, 0x94, 0xc0, 0xc0, 0x43, 0xf7, 0x61, 0xc9, 0x70, 0x9a, 0xe8, 0x5a, 0xc8, 0x30, 0x9a, 0xe0,
	0xca, 0xb5, 0xb1, 0xd5, 0x62, 0x1b, 0x7b, 0x00, 0xeb, 0x49, 0x3b, 0x1e, 0xb8, 0xe1, 0x90, 0x98,
	0xca, 0x54, 0x93, 0x95, 0x69, 0xd5, 0x74, 0xe6, 0x72, 0x4e, 0x17, 0xa7, 0x01, 0x6c, 0xe6, 0x64,
	0x12, 0xbf, 0x2f, 0x4e, 0xf3, 0xfb, 0x7a, 0x46, 0x51, 0x52, 0x43, 0x3f, 0x80, 0x8d, 0x64, 0xcf,
	0x23, 0x9e, 0x5e, 0xbf, 0x2e, 0xd7, 0x5f, 0x33, 0x3b, 0x57, 0x93, 0xda, 0x80, 0x2f, 0xc0, 0xca,
	0x4b, 0x25, 0x16, 0x34, 0xa6, 0x59, 0xb0, 0x91, 0x55, 0x95, 0x98, 0xf0, 0x35, 0x6c, 0x19, 0x65,
	0x3e, 0x66, 0xdc, 0x89, 0x55, 0x6f, 0x29, 0xaa, 0xa7, 0xaa, 0xcf, 0xb3, 0x03, 0xc2, 0xa8, 0xfd,
	0x29, 0x66, 0xdc, 0x36, 0xa2, 0x7d, 0x8e, 0x3e, 0x07, 0xe3, 0x0c, 0xd3, 0xcf, 0x36, 0x65, 0x2d,
	0xb8, 0x9d, 0xed, 0x67, 0x27, 0x68, 0x39, 0x69, 0x63, 0xdb, 0x51, 0x9a, 0x86, 0xfe, 0x1f, 0x54,
	0x53, 0xee, 0x78, 0x98, 0x63, 0x9d, 0xc6, 0x68, 0x12, 0x4b, 0x62, 0xea, 0x19, 0xe6, 0xd8, 0x6e,
	0x44, 0xe6, 0x2f, 0x7a, 0x5a, 0xb8, 0x9c, 0xb4, 0xa5, 0xd8, 0x76, 0x5a, 0x6c, 0x82, 0xce, 0x2a,
	0x10, 0x73, 0x37, 0x97, 0x1f, 0x41, 0x37, 0xab, 0xc3, 0xe1, 0x24, 0x1e, 0x52, 0x9d, 0xfe, 0xaa,
	0x57, 0xd8, 0xcc, 0x88, 0x9c, 0xe8, 0xf9, 0x81, 0x87, 0x3e, 0x84, 0xcd, 0x9c, 0x70, 0x12, 0xd2,
	0xea, 0x2e, 0xb1, 0x16, 0x15, 0x0c, 0x18, 0x78, 0xa8, 0x0f, 0x3b, 0x79, 0xb1, 0x6c, 0x54, 0x2c,
	0xcb, 0xa8, 0xe8, 0x66, 0x85, 0x33, 0xb1, 0xf1, 0x73, 0xb8, 0x35, 0x45, 0x45, 0x12, 0x22, 0x2b,
	0xd3, 0x42, 0xe4, 0x46, 0x99, 0xde, 0x24, 0x50, 0x3e, 0x83, 0x1b, 0x39, 0xcd, 0xd9, 0x8c, 0x41,
	0xd2, 0xb6, 0xad, 0x8c, 0x8e, 0x4c, 0xde, 0x7c, 0x03, 0x37, 0xcb, 0x15, 0x24, 0x96, 0xad, 0x4e,
	0xb3, 0x6c, 0xbb, 0x44, 0x6b, 0x62, 0xd8, 0xe7, 0x70, 0x7b, 0xb6, 0x5e, 0x07, 0x3f, 0x92, 0x0d,
	0x44, 0xc3, 0xde, 0x99, 0xa1, 0xa7, 0xff, 0x08, 0xfd, 0xba, 0x60, 0xa1, 0x72, 0x9b, 0xeb, 0x87,
	0x4c, 0x25, 0xc4, 0xfa, 0x1b, 0x13, 0xa2, 0x5b, 0xf4, 0xec, 0xa1, 0x14, 0xef, 0xf3, 0x14, 0x16,
	0x6f, 0x64, 0xb0, 0xf8, 0x87, 0x00, 0xea, 0x56, 0x21, 0xd7, 0xd8, 0x7c, 0xe3, 0x1a, 0x0d, 0xcd,
	0xdd, 0xe7, 0x42, 0x74, 0x14, 0x79, 0x46, 0xd4, 0x7a, 0xb3, 0xa8, 0xe6, 0xee, 0x73, 0x74, 0x0f,
	0x96, 0xf4, 0x45, 0xd0, 0x24, 0xbd, 0xb5, 0x25, 0xab, 0x49, 0x5b, 0x5d, 0x08, 0xcd, 0x93, 0xc5,
	0xe7, 0x70, 0x5b, 0xb9, 0xd8, 0x11, 0x0d, 0x3c, 0x8b, 0x0c, 0xe8, 0xd2, 0xe0, 0x7c, 0xe2, 0xba,
	0xae, 0xf4, 0xfe, 0x8e, 0x62, 0x1c, 0x04, 0xc7, 0x2c, 0xea, 0x27, 0x5c, 0x89, 0xa7, 0x6c, 0xb8,
	0x37, 0xd1, 0x64, 0xca, 0x6e, 0xa9, 0xba, 0x6d, 0xa9, 0xae, 0x67, 0xd4, 0x99, 0xaa, 0x5c, 0xa2,
	0xf3, 0x04, 0xee, 0x6b, 0x9d, 0xe1, 0x88, 0xcf, 0x56, 0x7a, 0x43, 0x2a, 0xbd, 0xa3, 0xd8, 0x5f,
	0x8e, 0xf8, 0x0c, 0xad, 0xdf, 0xc2, 0xc3, 0xd4, 0x9e, 0x75, 0x4c, 0xb0, 0x31, 0xe3, 0x64, 0x58,
	0xaa, 0x7a, 0x47, 0xaa, 0xbe, 0x9f, 0x6c, 0x5f, 0x49, 0x7c, 0x25, 0x05, 0x4a, 0xd4, 0x17, 0x73,
	0x49, 0x41, 0x9c, 0x29, 0x67, 0x37, 0x65, 0xb4, 0x66, 0x73, 0x49, 0x22, 0x9d, 0xa9, 0x6c, 0x04,
	0xb6, 0xf2, 0xe8, 0x74, 0x15, 0x18, 0xa4, 0xbd, 0x55, 0xf6, 0x72, 0x90, 0x85, 0xbc, 0x93, 0xab,
	0x20, 0x0d, 0xb9, 0x1b, 0x51, 0xe9, 0x24, 0x7a, 0x9c, 0xbf, 0x1b, 0xec, 0xe6, 0x4a, 0x79, 0xba,
	0x8f, 0xce, 0x5d, 0x07, 0x4e, 0x00, 0x19, 0x13, 0x45, 0x78, 0x51, 0x46, 0x39, 0x61, 0xd6, 0x6d,
	0x69, 0xdb, 0xdd, 0x72, 0xdb, 0xec, 0x84, 0x4f, 0x99, 0xb5, 0x12, 0xe5, 0xe9, 0xe8, 0x31, 0x74,
	0x44, 0x08, 0x9e, 0x91, 0x04, 0x77, 0x7a, 0xd2, 0xa4, 0xb5, 0xac, 0xc6, 0x23, 0x42, 0x8e, 0x59,
	0x64, 0xb7, 0x22, 0x16, 0x1d, 0x11, 0x03, 0x40, 0x9f, 0x01, 0x32, 0x35, 0x29, 0x25, 0x7f, 0x27,
	0x07, 0x3a, 0x46, 0xde, 0x36, 0xed, 0xc8, 0x44, 0xc1, 0x13, 0x58, 0xe5, 0xa1, 0x76, 0x55, 0x4a,
	0xc3, 0x3b, 0x53, 0x35, 0xf0, 0x50, 0x7a, 0x6d, 0xa2, 0x61, 0x07, 0x40, 0xb4, 0x7c, 0x5a, 0xf0,
	0xae, 0x8c, 0x9a, 0xc6, 0x25, 0x36, 0xf7, 0xde, 0x5f, 0x4c, 0xdc, 0xaa, 0x83, 0x2d, 0xb5, 0xcc,
	0xbd, 0xdc, 0x45, 0x23, 0xd9, 0x68, 0x3a, 0xd8, 0x12, 0x57, 0xaa, 0x61, 0xb2, 0x72, 0xf7, 0x09,
	0xa0, 0x62, 0xad, 0xbd, 0xd6, 0x2b, 0xcf, 0x00, 0xb6, 0x67, 0xc4, 0xd0, 0xb5, 0x54, 0x3d, 0x83,
	0x8d, 0x72, 0x97, 0x5f, 0xeb, 0xe1, 0xe8, 0x57, 0x50, 0x4f, 0x32, 0x6a, 0x0b, 0xea, 0x6e, 0xe8,
	0x11, 0x87, 0x06, 0x5c, 0x0a, 0x57, 0xed, 0x45, 0x31, 0x1e, 0x04, 0x1c, 0x6d, 0x82, 0xfc, 0x2b,
	0xaa, 0x80, 0x52, 0x51, 0x13, 0xc3, 0xfe, 0xa3, 0xec, 0x0d, 0xb3, 0x9a, 0xbd, 0x61, 0xf6, 0x7e,
	0x3f, 0x07, 0x8d, 0xa4, 0xb9, 0x90, 0xdd, 0x6d, 0x94, 0x74, 0xb7, 0x91, 0xc0, 0x4e, 0x99, 0x88,
	0xf1, 0xd8, 0x51, 0xba, 0x0f, 0xb4, 0xee, 0xb6, 0x26, 0x1f, 0x8a, 0x25, 0x0e, 0xd0, 0xfb, 0xd0,
	0x32, 0x7c, 0xf2, 0x4a, 0xa7, 0x2e, 0x06, 0xed, 0xc4, 0x87, 0x2f, 0xf0, 0x90, 0xd8, 0x4d, 0xcd,
	0x22, 0xdf, 0x95, 0x6f, 0xc3, 0x82, 0x4b, 0xb9, 0x7a, 0xc7, 0x2d, 0x70, 0xca, 0x29, 0xd1, 0xd6,
	0xb2, 0xd1, 0xa9, 0x47, 0x2f, 0x29, 0x4b, 0xb5, 0xb5, 0x29, 0x12, 0xea, 0x42, 0x9d, 0xd3, 0x21,
	0xf9, 0x6d, 0x18, 0x10, 0x7d, 0x95, 0x4b, 0xc6, 0xe2, 0x3c, 0xd5, 0x8b, 0xa7, 0x7a, 0xd5, 0x55,
	0x03, 0x41, 0x55, 0x77, 0x3a, 0x75, 0x4f, 0x53, 0x83, 0xde, 0x3f, 0x2a, 0x80, 0x8a, 0xad, 0x52,
	0xa1, 0xd7, 0x2f, 0xbb, 0xb0, 0x7e, 0x00, 0x35, 0x0d, 0x47, 0x6a, 0xcf, 0x37, 0xca, 0x7b, 0x2f,
	0x15, 0x41, 0xb6, 0xe6, 0x45, 0x9f, 0x4c, 0x3a, 0x37, 0x95, 0x00, 0xfa, 0x1c, 0x36, 0xf2, 0xd2,
	0x3a, 0xda, 0xdb, 0x99, 0x68, 0x17, 0x97, 0xb4, 0xf3, 0x38, 0x1c, 0x45, 0x0e, 0xf6, 0x29, 0x66,
	0xfa, 0x64, 0x40, 0x92, 0xfa, 0x82, 0xd2, 0xfb, 0x57, 0x25, 0x77, 0xbf, 0xd7, 0x40, 0x67, 0xc1,
	0xe2, 0x05, 0x0e, 0x3c, 0x9f, 0xc4, 0x7a, 0x5b, 0x66, 0x28, 0x8f, 0x52, 0x37, 0x76, 0x7a, 0x7f,
	0xc9, 0x38, 0x7f, 0x27, 0x9c, 0x2f, 0xdc, 0x09, 0x3f, 0x31, 0xef, 0xc1, 0x0b, 0x12, 0xf6, 0xee,
	0xcf, 0x3a, 0x83, 0xe2, 0x83, 0xf0, 0xff, 0xfe, 0x22, 0xdb, 0xfb, 0x5d, 0x05, 0xda, 0x99, 0x93,
	0x2a, 0xdc, 0x67, 0x9f, 0xc2, 0x6a, 0x59, 0x21, 0x5b, 0x98, 0xd6, 0x82, 0x21, 0x5c, 0x2c, 0x63,
	0x99, 0x04, 0xaa, 0xe5, 0x12, 0xe8, 0x8f, 0x15, 0x68, 0xa5, 0xcb, 0xc3, 0x5b, 0x45, 0xcd, 0x6d,
	0x68, 0x25, 0x5d, 0x1b, 0xd5, 0xdf, 0x39, 0xaa, 0x76, 0xd3, 0xd0, 0x44, 0x3a, 0x8b, 0xf8, 0x8d,
	0xa9, 0x4b, 0xa4, 0xa9, 0x15, 0x5b, 0x0d, 0x66, 0xe7, 0xf2, 0x17, 0xd0, 0xce, 0x3c, 0xf8, 0x14,
	0xeb, 0x5a, 0x45, 0xfa, 0xe7, 0x6d, 0xea, 0x5a, 0xef, 0x0f, 0x15, 0xa8, 0x1b, 0xe8, 0x45, 0x4f,
	0x60, 0x5b, 0xe1, 0x6b, 0xc6, 0xa1, 0xe6, 0x80, 0xe4, 0x66, 0x2b, 0xf6, 0x2c, 0x16, 0xf4, 0x03,
	0xd8, 0x50, 0xd3, 0xa6, 0x1b, 0x39, 0x4c, 0x3f, 0x73, 0x57, 0xec, 0x29, 0xb3, 0xbd, 0xbf, 0x57,
	0xa0, 0x99, 0x2a, 0x75, 0xdf, 0x9f, 0x25, 0xe8, 0x21, 0xac, 0x68, 0xb5, 0x2c, 0x3a, 0x4c, 0xbf,
	0x80, 0x54, 0xec, 0xe2, 0x44, 0xef, 0x9f, 0x15, 0x58, 0x2f, 0xad, 0x5c, 0xdf, 0xe3, 0x0e, 0xf2,
	0x2b, 0x2b, 0x83, 0x72, 0x7b, 0x99, 0xc5, 0xd2, 0xfb, 0x16, 0xd6, 0xca, 0xde, 0xfd, 0x0a, 0x31,
	0xff, 0x21, 0xd4, 0xb1, 0xe7, 0xa9, 0x66, 0x7d, 0xee, 0x8d, 0xcd, 0xfa, 0xa2, 0xe4, 0xed, 0xf3,
	0x9e, 0x03, 0xeb, 0xa5, 0xcf, 0x8a, 0xe8, 0xa8, 0xf8, 0xe6, 0xaa, 0x42, 0x79, 0x67, 0xe6, 0x7b,
	0x64, 0xfe, 0xb1, 0xb5, 0xf7, 0xe7, 0x0a, 0xb4, 0x92, 0x54, 0xc7, 0x9c, 0x14, 0xe0, 0xe2, 0x0e,
	0xb4, 0x93, 0xc4, 0x3c, 0x8b, 0xc3, 0xa1, 0xb4, 0xbe, 0x6a, 0x27, 0xd9, 0x7a, 0x14, 0x87, 0x12,
	0x7e, 0x13, 0x26, 0x1e, 0xea, 0xe4, 0x05, 0x43, 0x3a, 0x09, 0x45, 0xca, 0xc7, 0x98, 0x9b, 0xd4,
	0x95, 0xff, 0x67, 0x67, 0xee, 0x9f, 0xe6, 0x13, 0x1c, 0x2b, 0x9c, 0xa8, 0x32, 0x6c, 0x0d, 0xaa,
	0x12, 0xdf, 0x0d, 0x06, 0xca, 0x01, 0xba, 0x09, 0x66, 0x59, 0x4a, 0x44, 0x05, 0x9a, 0x4f, 0x19,
	0x42, 0x09, 0x9b, 0xf2, 0x39, 0x62, 0x61, 0xca, 0xe7, 0x88, 0xf2, 0x4f, 0x1d, 0xd5, 0x29, 0x9f,
	0x3a, 0x26, 0x95, 0xaf, 0x76, 0x8d, 0xca, 0x87, 0x60, 0x61, 0xe0, 0x26, 0xdf, 0x5a, 0xe5, 0xff,
	0x92, 0x6a, 0x58, 0xbf, 0x4e, 0x35, 0x44, 0xb0, 0xc0, 0xc7, 0x11, 0xd1, 0x8f, 0xa9, 0xf2, 0x3f,
	0xba, 0x0b, 0x1d, 0x0d, 0xe4, 0x4e, 0x4c, 0xce, 0xc9, 0x55, 0xa4, 0x1f, 0x4f, 0xdb, 0x9a, 0x6a,
	0x4b, 0x62, 0xd6, 0x29, 0xcd, 0xac, 0x53, 0x9e, 0xf6, 0x7f, 0xf9, 0xd9, 0x39, 0xe5, 0x17, 0xa3,
	0xd3, 0x3d, 0x37, 0x1c, 0xee, 0x9b, 0xd7, 0xd6, 0x97, 0x2f, 0x9e, 0xef, 0x47, 0x78, 0x1c, 0x06,
	0xe4, 0x3d, 0x6d, 0xdd, 0x7b, 0x8c, 0xc4, 0x97, 0xd4, 0x25, 0xfb, 0xd1, 0xab, 0x73, 0xf5, 0x41,
	0xdd, 0x7c, 0x75, 0x3f, 0xad, 0xc9, 0xe1, 0xa3, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x83, 0x75,
	0xe4, 0x74, 0x8f, 0x1f, 0x00, 0x00,
}
