// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billing/cardpay.proto

package billing // import "github.com/ProtocolONE/payone-billing-service/pkg/proto/billing"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CardPayAddress struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Street               string   `protobuf:"bytes,5,opt,name=street,proto3" json:"street,omitempty"`
	Zip                  string   `protobuf:"bytes,6,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayAddress) Reset()         { *m = CardPayAddress{} }
func (m *CardPayAddress) String() string { return proto.CompactTextString(m) }
func (*CardPayAddress) ProtoMessage()    {}
func (*CardPayAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{0}
}
func (m *CardPayAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayAddress.Unmarshal(m, b)
}
func (m *CardPayAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayAddress.Marshal(b, m, deterministic)
}
func (dst *CardPayAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayAddress.Merge(dst, src)
}
func (m *CardPayAddress) XXX_Size() int {
	return xxx_messageInfo_CardPayAddress.Size(m)
}
func (m *CardPayAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayAddress.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayAddress proto.InternalMessageInfo

func (m *CardPayAddress) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CardPayAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CardPayAddress) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CardPayAddress) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CardPayAddress) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CardPayAddress) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type CardPayItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayItem) Reset()         { *m = CardPayItem{} }
func (m *CardPayItem) String() string { return proto.CompactTextString(m) }
func (*CardPayItem) ProtoMessage()    {}
func (*CardPayItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{1}
}
func (m *CardPayItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayItem.Unmarshal(m, b)
}
func (m *CardPayItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayItem.Marshal(b, m, deterministic)
}
func (dst *CardPayItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayItem.Merge(dst, src)
}
func (m *CardPayItem) XXX_Size() int {
	return xxx_messageInfo_CardPayItem.Size(m)
}
func (m *CardPayItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayItem.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayItem proto.InternalMessageInfo

func (m *CardPayItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CardPayItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CardPayItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CardPayItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CardPayMerchantOrder struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Items                []*CardPayItem  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	ShippingAddress      *CardPayAddress `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CardPayMerchantOrder) Reset()         { *m = CardPayMerchantOrder{} }
func (m *CardPayMerchantOrder) String() string { return proto.CompactTextString(m) }
func (*CardPayMerchantOrder) ProtoMessage()    {}
func (*CardPayMerchantOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{2}
}
func (m *CardPayMerchantOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayMerchantOrder.Unmarshal(m, b)
}
func (m *CardPayMerchantOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayMerchantOrder.Marshal(b, m, deterministic)
}
func (dst *CardPayMerchantOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayMerchantOrder.Merge(dst, src)
}
func (m *CardPayMerchantOrder) XXX_Size() int {
	return xxx_messageInfo_CardPayMerchantOrder.Size(m)
}
func (m *CardPayMerchantOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayMerchantOrder.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayMerchantOrder proto.InternalMessageInfo

func (m *CardPayMerchantOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardPayMerchantOrder) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CardPayMerchantOrder) GetItems() []*CardPayItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *CardPayMerchantOrder) GetShippingAddress() *CardPayAddress {
	if m != nil {
		return m.ShippingAddress
	}
	return nil
}

type CallbackCardPayBankCardAccount struct {
	Holder               string   `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	IssuingCountryCode   string   `protobuf:"bytes,2,opt,name=issuing_country_code,json=issuingCountryCode,proto3" json:"issuing_country_code,omitempty"`
	MaskedPan            string   `protobuf:"bytes,3,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackCardPayBankCardAccount) Reset()         { *m = CallbackCardPayBankCardAccount{} }
func (m *CallbackCardPayBankCardAccount) String() string { return proto.CompactTextString(m) }
func (*CallbackCardPayBankCardAccount) ProtoMessage()    {}
func (*CallbackCardPayBankCardAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{3}
}
func (m *CallbackCardPayBankCardAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackCardPayBankCardAccount.Unmarshal(m, b)
}
func (m *CallbackCardPayBankCardAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackCardPayBankCardAccount.Marshal(b, m, deterministic)
}
func (dst *CallbackCardPayBankCardAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackCardPayBankCardAccount.Merge(dst, src)
}
func (m *CallbackCardPayBankCardAccount) XXX_Size() int {
	return xxx_messageInfo_CallbackCardPayBankCardAccount.Size(m)
}
func (m *CallbackCardPayBankCardAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackCardPayBankCardAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackCardPayBankCardAccount proto.InternalMessageInfo

func (m *CallbackCardPayBankCardAccount) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

func (m *CallbackCardPayBankCardAccount) GetIssuingCountryCode() string {
	if m != nil {
		return m.IssuingCountryCode
	}
	return ""
}

func (m *CallbackCardPayBankCardAccount) GetMaskedPan() string {
	if m != nil {
		return m.MaskedPan
	}
	return ""
}

func (m *CallbackCardPayBankCardAccount) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CallbackCardPayCryptoCurrencyAccount struct {
	CryptoAddress        string   `protobuf:"bytes,1,opt,name=crypto_address,json=cryptoAddress,proto3" json:"crypto_address,omitempty"`
	CryptoTransactionId  string   `protobuf:"bytes,2,opt,name=crypto_transaction_id,json=cryptoTransactionId,proto3" json:"crypto_transaction_id,omitempty"`
	PrcAmount            string   `protobuf:"bytes,3,opt,name=prc_amount,json=prcAmount,proto3" json:"prc_amount,omitempty"`
	PrcCurrency          string   `protobuf:"bytes,4,opt,name=prc_currency,json=prcCurrency,proto3" json:"prc_currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackCardPayCryptoCurrencyAccount) Reset()         { *m = CallbackCardPayCryptoCurrencyAccount{} }
func (m *CallbackCardPayCryptoCurrencyAccount) String() string { return proto.CompactTextString(m) }
func (*CallbackCardPayCryptoCurrencyAccount) ProtoMessage()    {}
func (*CallbackCardPayCryptoCurrencyAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{4}
}
func (m *CallbackCardPayCryptoCurrencyAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.Unmarshal(m, b)
}
func (m *CallbackCardPayCryptoCurrencyAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.Marshal(b, m, deterministic)
}
func (dst *CallbackCardPayCryptoCurrencyAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.Merge(dst, src)
}
func (m *CallbackCardPayCryptoCurrencyAccount) XXX_Size() int {
	return xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.Size(m)
}
func (m *CallbackCardPayCryptoCurrencyAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackCardPayCryptoCurrencyAccount proto.InternalMessageInfo

func (m *CallbackCardPayCryptoCurrencyAccount) GetCryptoAddress() string {
	if m != nil {
		return m.CryptoAddress
	}
	return ""
}

func (m *CallbackCardPayCryptoCurrencyAccount) GetCryptoTransactionId() string {
	if m != nil {
		return m.CryptoTransactionId
	}
	return ""
}

func (m *CallbackCardPayCryptoCurrencyAccount) GetPrcAmount() string {
	if m != nil {
		return m.PrcAmount
	}
	return ""
}

func (m *CallbackCardPayCryptoCurrencyAccount) GetPrcCurrency() string {
	if m != nil {
		return m.PrcCurrency
	}
	return ""
}

type CardPayCustomer struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Locale               string   `protobuf:"bytes,4,opt,name=locale,proto3" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayCustomer) Reset()         { *m = CardPayCustomer{} }
func (m *CardPayCustomer) String() string { return proto.CompactTextString(m) }
func (*CardPayCustomer) ProtoMessage()    {}
func (*CardPayCustomer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{5}
}
func (m *CardPayCustomer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayCustomer.Unmarshal(m, b)
}
func (m *CardPayCustomer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayCustomer.Marshal(b, m, deterministic)
}
func (dst *CardPayCustomer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayCustomer.Merge(dst, src)
}
func (m *CardPayCustomer) XXX_Size() int {
	return xxx_messageInfo_CardPayCustomer.Size(m)
}
func (m *CardPayCustomer) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayCustomer.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayCustomer proto.InternalMessageInfo

func (m *CardPayCustomer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CardPayCustomer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CardPayCustomer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CardPayCustomer) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type CardPayEWalletAccount struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardPayEWalletAccount) Reset()         { *m = CardPayEWalletAccount{} }
func (m *CardPayEWalletAccount) String() string { return proto.CompactTextString(m) }
func (*CardPayEWalletAccount) ProtoMessage()    {}
func (*CardPayEWalletAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{6}
}
func (m *CardPayEWalletAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayEWalletAccount.Unmarshal(m, b)
}
func (m *CardPayEWalletAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayEWalletAccount.Marshal(b, m, deterministic)
}
func (dst *CardPayEWalletAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayEWalletAccount.Merge(dst, src)
}
func (m *CardPayEWalletAccount) XXX_Size() int {
	return xxx_messageInfo_CardPayEWalletAccount.Size(m)
}
func (m *CardPayEWalletAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayEWalletAccount.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayEWalletAccount proto.InternalMessageInfo

func (m *CardPayEWalletAccount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CallbackCardPayPaymentData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	AuthCode             string   `protobuf:"bytes,3,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	Created              string   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Currency             string   `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DeclineCode          string   `protobuf:"bytes,6,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	DeclineReason        string   `protobuf:"bytes,7,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Is_3D                bool     `protobuf:"varint,9,opt,name=is_3d,json=is3d,proto3" json:"is_3d,omitempty"`
	Note                 string   `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	Rrn                  string   `protobuf:"bytes,11,opt,name=rrn,proto3" json:"rrn,omitempty"`
	Status               string   `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackCardPayPaymentData) Reset()         { *m = CallbackCardPayPaymentData{} }
func (m *CallbackCardPayPaymentData) String() string { return proto.CompactTextString(m) }
func (*CallbackCardPayPaymentData) ProtoMessage()    {}
func (*CallbackCardPayPaymentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{7}
}
func (m *CallbackCardPayPaymentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackCardPayPaymentData.Unmarshal(m, b)
}
func (m *CallbackCardPayPaymentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackCardPayPaymentData.Marshal(b, m, deterministic)
}
func (dst *CallbackCardPayPaymentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackCardPayPaymentData.Merge(dst, src)
}
func (m *CallbackCardPayPaymentData) XXX_Size() int {
	return xxx_messageInfo_CallbackCardPayPaymentData.Size(m)
}
func (m *CallbackCardPayPaymentData) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackCardPayPaymentData.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackCardPayPaymentData proto.InternalMessageInfo

func (m *CallbackCardPayPaymentData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CallbackCardPayPaymentData) GetAuthCode() string {
	if m != nil {
		return m.AuthCode
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetDeclineCode() string {
	if m != nil {
		return m.DeclineCode
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetDeclineReason() string {
	if m != nil {
		return m.DeclineReason
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetIs_3D() bool {
	if m != nil {
		return m.Is_3D
	}
	return false
}

func (m *CallbackCardPayPaymentData) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetRrn() string {
	if m != nil {
		return m.Rrn
	}
	return ""
}

func (m *CallbackCardPayPaymentData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CardPayPaymentCallback struct {
	MerchantOrder         *CardPayMerchantOrder                 `protobuf:"bytes,1,opt,name=merchant_order,json=merchantOrder,proto3" json:"merchant_order,omitempty"`
	PaymentMethod         string                                `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	CallbackTime          string                                `protobuf:"bytes,3,opt,name=callback_time,json=callbackTime,proto3" json:"callback_time,omitempty"`
	CardAccount           *CallbackCardPayBankCardAccount       `protobuf:"bytes,4,opt,name=card_account,json=cardAccount,proto3" json:"card_account,omitempty"`
	CryptocurrencyAccount *CallbackCardPayCryptoCurrencyAccount `protobuf:"bytes,5,opt,name=cryptocurrency_account,json=cryptocurrencyAccount,proto3" json:"cryptocurrency_account,omitempty"`
	Customer              *CardPayCustomer                      `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	EwalletAccount        *CardPayEWalletAccount                `protobuf:"bytes,7,opt,name=ewallet_account,json=ewalletAccount,proto3" json:"ewallet_account,omitempty"`
	PaymentData           *CallbackCardPayPaymentData           `protobuf:"bytes,8,opt,name=payment_data,json=paymentData,proto3" json:"payment_data,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                              `json:"-"`
	XXX_unrecognized      []byte                                `json:"-"`
	XXX_sizecache         int32                                 `json:"-"`
}

func (m *CardPayPaymentCallback) Reset()         { *m = CardPayPaymentCallback{} }
func (m *CardPayPaymentCallback) String() string { return proto.CompactTextString(m) }
func (*CardPayPaymentCallback) ProtoMessage()    {}
func (*CardPayPaymentCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_cardpay_9b7877d5edcaa1cd, []int{8}
}
func (m *CardPayPaymentCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardPayPaymentCallback.Unmarshal(m, b)
}
func (m *CardPayPaymentCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardPayPaymentCallback.Marshal(b, m, deterministic)
}
func (dst *CardPayPaymentCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardPayPaymentCallback.Merge(dst, src)
}
func (m *CardPayPaymentCallback) XXX_Size() int {
	return xxx_messageInfo_CardPayPaymentCallback.Size(m)
}
func (m *CardPayPaymentCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_CardPayPaymentCallback.DiscardUnknown(m)
}

var xxx_messageInfo_CardPayPaymentCallback proto.InternalMessageInfo

func (m *CardPayPaymentCallback) GetMerchantOrder() *CardPayMerchantOrder {
	if m != nil {
		return m.MerchantOrder
	}
	return nil
}

func (m *CardPayPaymentCallback) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *CardPayPaymentCallback) GetCallbackTime() string {
	if m != nil {
		return m.CallbackTime
	}
	return ""
}

func (m *CardPayPaymentCallback) GetCardAccount() *CallbackCardPayBankCardAccount {
	if m != nil {
		return m.CardAccount
	}
	return nil
}

func (m *CardPayPaymentCallback) GetCryptocurrencyAccount() *CallbackCardPayCryptoCurrencyAccount {
	if m != nil {
		return m.CryptocurrencyAccount
	}
	return nil
}

func (m *CardPayPaymentCallback) GetCustomer() *CardPayCustomer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *CardPayPaymentCallback) GetEwalletAccount() *CardPayEWalletAccount {
	if m != nil {
		return m.EwalletAccount
	}
	return nil
}

func (m *CardPayPaymentCallback) GetPaymentData() *CallbackCardPayPaymentData {
	if m != nil {
		return m.PaymentData
	}
	return nil
}

func init() {
	proto.RegisterType((*CardPayAddress)(nil), "billing.CardPayAddress")
	proto.RegisterType((*CardPayItem)(nil), "billing.CardPayItem")
	proto.RegisterType((*CardPayMerchantOrder)(nil), "billing.CardPayMerchantOrder")
	proto.RegisterType((*CallbackCardPayBankCardAccount)(nil), "billing.CallbackCardPayBankCardAccount")
	proto.RegisterType((*CallbackCardPayCryptoCurrencyAccount)(nil), "billing.CallbackCardPayCryptoCurrencyAccount")
	proto.RegisterType((*CardPayCustomer)(nil), "billing.CardPayCustomer")
	proto.RegisterType((*CardPayEWalletAccount)(nil), "billing.CardPayEWalletAccount")
	proto.RegisterType((*CallbackCardPayPaymentData)(nil), "billing.CallbackCardPayPaymentData")
	proto.RegisterType((*CardPayPaymentCallback)(nil), "billing.CardPayPaymentCallback")
}

func init() { proto.RegisterFile("billing/cardpay.proto", fileDescriptor_cardpay_9b7877d5edcaa1cd) }

var fileDescriptor_cardpay_9b7877d5edcaa1cd = []byte{
	// 888 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0x86, 0x24, 0x4b, 0xb6, 0x66, 0x65, 0x39, 0x60, 0x6c, 0x75, 0x91, 0x22, 0x81, 0xbb, 0xa9,
	0x11, 0xa3, 0x80, 0xad, 0x42, 0xee, 0xbd, 0xb0, 0x95, 0xb4, 0x48, 0x81, 0x34, 0xc6, 0x22, 0x40,
	0x81, 0x5e, 0x16, 0x34, 0x49, 0x58, 0x84, 0x77, 0x49, 0x82, 0x4b, 0xb5, 0x50, 0x9f, 0xa3, 0xf7,
	0x1e, 0xfa, 0x12, 0xbd, 0xf7, 0x1d, 0xfa, 0x3c, 0x05, 0xc9, 0xa1, 0x22, 0x29, 0x4d, 0x91, 0xdb,
	0x7e, 0x1f, 0xc9, 0x99, 0x6f, 0x7e, 0x17, 0x4e, 0xee, 0x64, 0x5d, 0x4b, 0x75, 0x3f, 0x65, 0xd4,
	0x72, 0x43, 0x57, 0x97, 0xc6, 0x6a, 0xa7, 0xc9, 0x3e, 0xd2, 0xc5, 0xef, 0x1d, 0x18, 0xcf, 0xa9,
	0xe5, 0xb7, 0x74, 0x75, 0xcd, 0xb9, 0x15, 0x6d, 0x4b, 0x72, 0xd8, 0x67, 0x7a, 0xa9, 0x9c, 0x5d,
	0xe5, 0x9d, 0xd3, 0xce, 0xf9, 0xb0, 0x4c, 0x90, 0x10, 0xd8, 0x63, 0xd2, 0xad, 0xf2, 0x6e, 0xa0,
	0xc3, 0x37, 0x39, 0x86, 0xbe, 0x59, 0x68, 0x25, 0xf2, 0x5e, 0x20, 0x23, 0xf0, 0x6c, 0xeb, 0xa8,
	0x13, 0xf9, 0x5e, 0x64, 0x03, 0x20, 0x13, 0x18, 0xb4, 0xce, 0x0a, 0xe1, 0xf2, 0x7e, 0xa0, 0x11,
	0x91, 0x47, 0xd0, 0xfb, 0x4d, 0x9a, 0x7c, 0x10, 0x48, 0xff, 0x59, 0x68, 0xc8, 0x50, 0xd5, 0x6b,
	0x27, 0x1a, 0xef, 0x58, 0xd1, 0x46, 0xa0, 0x9e, 0xf0, 0x4d, 0x4e, 0x21, 0xe3, 0xa2, 0x65, 0x56,
	0x1a, 0x27, 0xb5, 0x42, 0x4d, 0x9b, 0x94, 0x17, 0x11, 0x94, 0x07, 0x69, 0xfd, 0x32, 0x82, 0x20,
	0xd8, 0x4a, 0x16, 0xa5, 0x75, 0xca, 0x08, 0x8a, 0xbf, 0x3a, 0x70, 0x8c, 0x1e, 0xdf, 0x08, 0xcb,
	0x16, 0x54, 0xb9, 0xb7, 0x96, 0x0b, 0x4b, 0xc6, 0xd0, 0x95, 0x1c, 0x1d, 0x77, 0x25, 0xff, 0x04,
	0xb7, 0x5f, 0x41, 0x5f, 0x3a, 0xd1, 0xb4, 0x79, 0xef, 0xb4, 0x77, 0x9e, 0xcd, 0x8e, 0x2f, 0x31,
	0xd7, 0x97, 0x1b, 0x11, 0x95, 0xf1, 0x0a, 0xb9, 0x81, 0x47, 0xed, 0x42, 0x1a, 0x23, 0xd5, 0x7d,
	0x45, 0x63, 0xfe, 0x83, 0xae, 0x6c, 0xf6, 0xd9, 0xee, 0x33, 0x2c, 0x4f, 0x79, 0x94, 0x1e, 0x20,
	0x51, 0xfc, 0xd1, 0x81, 0x67, 0x73, 0x5a, 0xd7, 0x77, 0x94, 0x3d, 0xe0, 0xdd, 0x1b, 0xaa, 0xc2,
	0xe7, 0x35, 0x8b, 0x31, 0x4f, 0x60, 0xb0, 0xd0, 0x35, 0x17, 0x16, 0x03, 0x41, 0x44, 0xbe, 0x86,
	0x63, 0xd9, 0xb6, 0x4b, 0xef, 0x1d, 0x6b, 0x5c, 0x31, 0xcd, 0x05, 0x46, 0x45, 0xf0, 0x6c, 0x1e,
	0x8f, 0xe6, 0x9a, 0x0b, 0xf2, 0x14, 0xa0, 0xa1, 0xed, 0x83, 0xe0, 0x95, 0xa1, 0x0a, 0x6b, 0x3e,
	0x8c, 0xcc, 0x2d, 0x0d, 0x29, 0x77, 0xfa, 0x41, 0xa8, 0x54, 0xf7, 0x00, 0x8a, 0xbf, 0x3b, 0xf0,
	0xe5, 0x8e, 0xc2, 0xb9, 0x5d, 0x19, 0xa7, 0xe7, 0x4b, 0x6b, 0x85, 0x62, 0xab, 0xa4, 0xf3, 0x0c,
	0xc6, 0x2c, 0x1c, 0xac, 0x93, 0x11, 0xf5, 0x1e, 0x46, 0x36, 0x75, 0xe8, 0x0c, 0x4e, 0xf0, 0x9a,
	0xb3, 0x54, 0xb5, 0x94, 0xf9, 0xbc, 0x57, 0x92, 0xa3, 0xee, 0xc7, 0xf1, 0xf0, 0xdd, 0xfb, 0xb3,
	0xd7, 0xdc, 0x0b, 0x37, 0x96, 0x55, 0xb4, 0x59, 0x77, 0xc4, 0xb0, 0x1c, 0x1a, 0xcb, 0xae, 0x03,
	0x41, 0xbe, 0x80, 0x91, 0x3f, 0x66, 0x28, 0x08, 0xf5, 0x67, 0xc6, 0xb2, 0xa4, 0xb1, 0xa8, 0xe0,
	0x28, 0x89, 0x5f, 0xb6, 0x4e, 0x37, 0xc2, 0xfa, 0x70, 0x45, 0x43, 0x65, 0x8d, 0x32, 0x23, 0x08,
	0x2d, 0x63, 0x50, 0x4b, 0x57, 0x1a, 0x6c, 0xa1, 0xde, 0xba, 0x85, 0x26, 0x30, 0xa8, 0x35, 0xa3,
	0x75, 0x9a, 0x0e, 0x44, 0xc5, 0x0b, 0x38, 0x41, 0x07, 0xaf, 0x7e, 0xa2, 0x75, 0x2d, 0x5c, 0x4a,
	0xcb, 0x4e, 0x0f, 0x16, 0xff, 0x74, 0xe1, 0xc9, 0x4e, 0x3e, 0x6f, 0xe9, 0xaa, 0x11, 0xca, 0xbd,
	0xa4, 0x8e, 0x7e, 0xd0, 0xb2, 0x13, 0x18, 0x60, 0xd8, 0xdd, 0xd0, 0xf2, 0x88, 0xc8, 0xe7, 0x30,
	0xa4, 0x4b, 0xb7, 0x88, 0x25, 0x8f, 0xf2, 0x0e, 0x3c, 0x11, 0x0a, 0xed, 0xb7, 0x80, 0x15, 0xd4,
	0x09, 0x8e, 0x2a, 0x13, 0x24, 0x4f, 0xe0, 0x60, 0x9d, 0xa6, 0x38, 0xc7, 0x6b, 0xec, 0xd3, 0xc8,
	0x05, 0xab, 0xa5, 0x12, 0xd1, 0xea, 0x20, 0x8d, 0x47, 0xe0, 0x82, 0xe1, 0x33, 0x18, 0xa7, 0x2b,
	0x56, 0xd0, 0x56, 0xab, 0x7c, 0x3f, 0xd6, 0x18, 0xd9, 0x32, 0x90, 0xbb, 0x73, 0x76, 0xf0, 0xe1,
	0x9c, 0x3d, 0x86, 0xbe, 0x6c, 0xab, 0x2b, 0x9e, 0x0f, 0x4f, 0x3b, 0xe7, 0x07, 0xe5, 0x9e, 0x6c,
	0xaf, 0x78, 0xd8, 0x14, 0xda, 0x89, 0x1c, 0x70, 0x53, 0x68, 0x27, 0xfc, 0x7a, 0xb1, 0x56, 0xe5,
	0x59, 0x5c, 0x2f, 0xd6, 0xaa, 0xb8, 0x88, 0xa8, 0x5b, 0xb6, 0xf9, 0x28, 0x2d, 0x22, 0x8f, 0x8a,
	0x3f, 0xf7, 0x60, 0xb2, 0x9d, 0xd0, 0x94, 0x66, 0xf2, 0x12, 0xc6, 0x0d, 0x2e, 0x86, 0x4a, 0xdb,
	0x34, 0x4a, 0xd9, 0xec, 0xe9, 0xee, 0x9c, 0x6e, 0xad, 0x8f, 0xf2, 0xb0, 0xd9, 0xda, 0x26, 0x67,
	0x30, 0x36, 0xd1, 0x70, 0xd5, 0x08, 0xb7, 0xd0, 0xa9, 0x65, 0x0f, 0x91, 0x7d, 0x13, 0x48, 0xf2,
	0x1c, 0x0e, 0x19, 0x3a, 0xae, 0x9c, 0x6c, 0x52, 0x75, 0x46, 0x89, 0x7c, 0x27, 0x1b, 0x41, 0x7e,
	0x80, 0x91, 0x5f, 0xea, 0x15, 0x8d, 0x5d, 0x82, 0x7b, 0xe3, 0xc5, 0x86, 0x9e, 0xff, 0xdb, 0x09,
	0x65, 0xc6, 0x36, 0x16, 0x04, 0x87, 0x49, 0x1c, 0x9a, 0x54, 0xc9, 0xb5, 0xd5, 0x7e, 0xb0, 0x7a,
	0xf1, 0x31, 0xab, 0xff, 0x39, 0xc7, 0xe5, 0xc9, 0xb6, 0xb1, 0xe4, 0xe5, 0x1b, 0xdf, 0x39, 0x71,
	0x74, 0x42, 0x67, 0x64, 0xb3, 0x7c, 0x37, 0x7b, 0x69, 0xb4, 0xca, 0xf5, 0x4d, 0xf2, 0x3d, 0x1c,
	0x89, 0x5f, 0xc3, 0x3c, 0xac, 0x45, 0xed, 0x87, 0xc7, 0xcf, 0x76, 0x1f, 0x6f, 0x8f, 0x4d, 0x39,
	0xc6, 0x67, 0xc9, 0xfd, 0x77, 0x30, 0x4a, 0xc9, 0xe7, 0xd4, 0xd1, 0xd0, 0x53, 0xd9, 0xec, 0xf9,
	0xc7, 0x42, 0xdb, 0x18, 0xa9, 0x32, 0x33, 0xef, 0xc1, 0xcd, 0xf5, 0xcf, 0xdf, 0xde, 0x4b, 0xb7,
	0x58, 0xde, 0x5d, 0x32, 0xdd, 0x4c, 0x6f, 0xfd, 0x0f, 0x95, 0xe9, 0xfa, 0xed, 0x8f, 0xaf, 0xa6,
	0x86, 0xae, 0xb4, 0x12, 0x17, 0x68, 0xf0, 0xa2, 0x15, 0xf6, 0x17, 0xc9, 0xc4, 0xd4, 0x3c, 0xdc,
	0x4f, 0xc3, 0x7f, 0x77, 0x8a, 0x27, 0x77, 0x83, 0x00, 0xaf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x59, 0x2f, 0x9a, 0x09, 0x9f, 0x07, 0x00, 0x00,
}
